/*
 * Footballer database for Link It FC.
 *
 * Two pools:
 *   STARTERS  — a hand-curated set of well-known players. Used to SEED the
 *               daily/free-play chain so you never start on an obscure name.
 *   SQUAD     — real tournament players (World Cup 1970+, Euros, Copa America),
 *               sourced from the public-domain openfootball dataset. Used,
 *               together with STARTERS, as the VALIDATION pool: any of these
 *               names is accepted as a valid link.
 *
 * The game treats the LAST word as the surname; the chain links the first
 * letter of one player's surname to the first letter of the next name.
 * Matching is accent-insensitive at runtime, so accents here are fine.
 */

const STARTERS = [
  "David Beckham", "Bryan Robson", "Rob Green", "Gary Neville",
  "Phil Neville", "Paul Scholes", "Ryan Giggs", "Roy Keane",
  "Eric Cantona", "Peter Schmeichel", "Wayne Rooney", "Steven Gerrard",
  "Frank Lampard", "John Terry", "Ashley Cole", "Rio Ferdinand",
  "Sol Campbell", "Gary Cahill", "Joe Cole", "Michael Owen",
  "Alan Shearer", "Teddy Sheringham", "Andy Cole", "Dwight Yorke",
  "Robbie Fowler", "Jamie Carragher", "Xabi Alonso", "Fernando Torres",
  "Luis Suarez", "Jamie Vardy", "Harry Kane", "Dele Alli",
  "Hugo Lloris", "Son Heungmin", "Gareth Bale", "Aaron Ramsey",
  "Cesc Fabregas", "Thierry Henry", "Patrick Vieira", "Dennis Bergkamp",
  "Robert Pires", "Freddie Ljungberg", "Sol Bamba", "Tony Adams",
  "David Seaman", "Ian Wright", "Paul Merson", "Ray Parlour",
  "Marc Overmars", "Nicolas Anelka", "Didier Drogba", "Petr Cech",
  "Michael Essien", "Claude Makelele", "Ashley Young", "Antonio Valencia",
  "Nemanja Vidic", "Patrice Evra", "Edwin van der Sar", "Park Jisung",
  "Carlos Tevez", "Sergio Aguero", "David Silva", "Yaya Toure",
  "Vincent Kompany", "Joe Hart", "Pablo Zabaleta", "Raheem Sterling",
  "Kevin De Bruyne", "Riyad Mahrez", "Ngolo Kante", "Eden Hazard",
  "Diego Costa", "Cesar Azpilicueta", "Thibaut Courtois", "Mohamed Salah",
  "Sadio Mane", "Roberto Firmino", "Virgil van Dijk", "Trent Alexander-Arnold",
  "Andy Robertson", "Jordan Henderson", "Alisson Becker", "Bukayo Saka",
  "Marcus Rashford", "Phil Foden", "Jack Grealish", "Mason Mount",
  "Declan Rice", "Jude Bellingham", "Jadon Sancho", "Reece James",
  "Ben White", "Harry Maguire", "Kalvin Phillips", "Jordan Pickford",
  "Kyle Walker", "John Stones", "Luke Shaw", "Eric Dier",
  "Paul Gascoigne", "Gary Lineker", "Chris Waddle", "Stuart Pearce",
  "David Platt", "Des Walker", "John Barnes", "Peter Beardsley",
  "Tony Cottee", "Matthew Le Tissier", "Les Ferdinand", "Ian Rush",
  "Kenny Dalglish", "Graeme Souness", "Alan Hansen", "Bryan Gunn",
  "Nigel Winterburn", "Lee Dixon", "Steve Bould", "Martin Keown",
  "Emile Heskey", "Darius Vassell", "Kieron Dyer", "Nicky Butt",
  "David James", "Lionel Messi", "Andres Iniesta", "Xavi Hernandez",
  "Carles Puyol", "Gerard Pique", "Sergio Busquets", "Sergio Ramos",
  "Iker Casillas", "Raul Gonzalez", "Fernando Hierro", "David Villa",
  "Pedro Rodriguez", "Jordi Alba", "Marc Bartra", "Victor Valdes",
  "Karim Benzema", "Luka Modric", "Toni Kroos", "Marcelo Vieira",
  "Isco Alarcon", "Gareth Southgate", "Antoine Griezmann", "Ousmane Dembele",
  "Frenkie de Jong", "Ronald Araujo", "Cristiano Ronaldo", "Luis Figo",
  "Rui Costa", "Nuno Gomes", "Pauleta", "Deco Souza",
  "Ricardo Carvalho", "Pepe Pereira", "Bruno Fernandes", "Bernardo Silva",
  "Joao Felix", "Diogo Jota", "Ruben Dias", "Joao Cancelo",
  "Rui Patricio", "Ronaldinho", "Ronaldo Nazario", "Rivaldo Borba",
  "Kaka", "Roberto Carlos", "Cafu", "Dida",
  "Adriano", "Robinho", "Neymar", "Dani Alves",
  "Thiago Silva", "Marquinhos", "Casemiro", "Vinicius Junior",
  "Gabriel Jesus", "Richarlison", "Philippe Coutinho", "Alex Sandro",
  "Ederson Moraes", "Diego Maradona", "Gabriel Batistuta", "Juan Riquelme",
  "Hernan Crespo", "Javier Zanetti", "Walter Samuel", "Esteban Cambiasso",
  "Angel Di Maria", "Gonzalo Higuain", "Javier Mascherano", "Paulo Dybala",
  "Lautaro Martinez", "Emiliano Martinez", "Rodrigo De Paul", "Nicolas Otamendi",
  "Zinedine Zidane", "Marcel Desailly", "Lilian Thuram", "Fabien Barthez",
  "Youri Djorkaeff", "Emmanuel Petit", "David Trezeguet", "Franck Ribery",
  "Kylian Mbappe", "Paul Pogba", "Olivier Giroud", "Raphael Varane",
  "Hugo Lloris", "Aurelien Tchouameni", "Eduardo Camavinga", "Paolo Maldini",
  "Alessandro Nesta", "Fabio Cannavaro", "Gianluigi Buffon", "Francesco Totti",
  "Andrea Pirlo", "Alessandro Del Piero", "Filippo Inzaghi", "Gennaro Gattuso",
  "Daniele De Rossi", "Giorgio Chiellini", "Leonardo Bonucci", "Marco Verratti",
  "Lorenzo Insigne", "Federico Chiesa", "Oliver Kahn", "Michael Ballack",
  "Miroslav Klose", "Lukas Podolski", "Bastian Schweinsteiger", "Philipp Lahm",
  "Manuel Neuer", "Mesut Ozil", "Thomas Muller", "Mats Hummels",
  "Jerome Boateng", "Marco Reus", "Toni Kroos", "Joshua Kimmich",
  "Kai Havertz", "Dennis Bergkamp", "Marc Overmars", "Edgar Davids",
  "Clarence Seedorf", "Patrick Kluivert", "Ruud van Nistelrooy", "Arjen Robben",
  "Robin van Persie", "Wesley Sneijder", "Rafael van der Vaart", "Memphis Depay",
  "Georginio Wijnaldum", "Matthijs de Ligt", "Frenkie de Jong", "Cody Gakpo",
  "George Weah", "Samuel Etoo", "Yaya Toure", "Jay Jay Okocha",
  "Nwankwo Kanu", "Michael Essien", "Asamoah Gyan", "Mohamed Aboutrika",
  "Sadio Mane", "Riyad Mahrez", "Zlatan Ibrahimovic", "Henrik Larsson",
  "Andriy Shevchenko", "Hristo Stoichkov", "Pavel Nedved", "Luka Modric",
  "Davor Suker", "Robert Lewandowski", "Erling Haaland", "Martin Odegaard",
  "Heung Min Son", "Shinji Kagawa", "Keisuke Honda", "Hidetoshi Nakata",
  "Park Jisung",
];

// Real tournament players (openfootball, public domain) — validation only.
const SQUAD = [
  "Aaron Clapham", "Aaron Lawrence", "Aaron Lennon", "Aaron Mokoena",
  "Aarón Padilla", "Abdallah Lamrani", "Abdelaziz Souleimani", "Abdelfettah Mouddani",
  "Abdelfettah Rhiati", "Abdelhamid Sadmi", "Abdelilah Saber", "Abdeljalil Hadda",
  "Abdelkader El Khiati", "Abdelkader Ghezzal", "Abdelkader Horr", "Abdelkader Laïfaoui",
  "Abdelkader Ouaraghli", "Abdelkrim El Hadrioui", "Abdelkrim Merry", "Abdellah Bidane",
  "Abdellah Medjadi Liegeon", "Abdelmajid Bourebbou", "Abdelmajid Bouyboud", "Abdelmajid Dolmy",
  "Abdelmajid Lamriss", "Abdelmoumene Djabou", "Abderrahim Ouakili", "Abderraouf Ben Aziza",
  "Abderrazak Dinar", "Abderrazak Khairi", "Abdeslam Laghrissi", "Abdoulaye Méïté",
  "Abdualla Sultan", "Abdul-Fatah Nasif Jassim", "Abdul Kader Keïta", "Abdul Rahim Ayew",
  "Abdul-Rahim Hamed Aufi", "Abdulaziz Al-Anberi", "Abdulaziz Al-Buloushi", "Abdulaziz Al-Janoubi",
  "Abdulaziz Khathran", "Abdulaziz Mohamed", "Abdullah Al-Buloushi", "Abdullah Al-Dosari",
  "Abdullah Al-Waked", "Abdullah Ercan", "Abdullah Jumaan Al-Dosari", "Abdullah Mayouf",
  "Abdullah Musa", "Abdullah Zubromawi", "Abdulqadir Hassan", "Abdulrahman Al-Haddad",
  "Abdulrahman Mohamed", "Abel", "Abel Aguilar", "Abel Balbo",
  "Abel Hernández", "Abel Xavier", "Abelardo", "Abelkader El Brazi",
  "Abiodun Baruwa", "Abou Diaby", "Acácio", "Achille Emana",
  "Adalbert Zafirov", "Adam Federici", "Adam Kwarasey", "Adam Lallana",
  "Adam Marjam", "Adam Matysek", "Adam Musiał", "Adam Nawałka",
  "Adam Taggart", "Adékambi Olufadé", "Adel Abdelrahman", "Adel Chedli",
  "Adel Nefzi", "Adel Sellimi", "Ademir da Guia", "Adlène Guedioura",
  "Admir Mehmedi", "Adnan Al Talyani", "Adnan Januzaj", "Ado",
  "Adolfino Cañete", "Adolfo Bautista", "Adolfo Nef", "Adolfo Valencia",
  "Adri van Tiggelen", "Adrian Alston", "Adrián Bone", "Adrián Chávez",
  "Adrian Elrick", "Adrian Ilie", "Adrian Knup", "Adrian Popescu",
  "Adrián Ramos", "Adrie van Kraay", "Affo Erassa", "Afriyie Acquah",
  "Afshin Peyrovani", "Agustín Aranzábal", "Agustín Balbuena", "Agustín Delgado",
  "Agustín Orión", "Ahmad Alenemeh", "Ahmad Jamil Madani", "Ahmad Jassim Mohammed",
  "Ahmad Radhi Amaiesh", "Ahmad Reza Abedzadeh", "Ahmed Al-Bahri", "Ahmed Al-Tarabulsi",
  "Ahmed Alaoui", "Ahmed Bahja", "Ahmed Dokhi", "Ahmed Dokhi Al-Dosari",
  "Ahmed El-Kass", "Ahmed Faras", "Ahmed Jaouachi", "Ahmed Masbahi",
  "Ahmed Musa", "Ahmed Ramzy", "Ahmed Shobair", "Ahn Jung-Hwan",
  "Aïssa Mandi", "Akhrik Tsveiba", "Akinori Nishizawa", "Akira Kaji",
  "Akira Narahashi", "Akwá", "Al Hasan Al-Yami", "Alaa Maihoub",
  "Alaeddine Yahia", "Alain Boghossian", "Alain Couriol", "Alain Geiger",
  "Alain Giresse", "Alain Sutter", "Alaixys Romao", "Alan Ball",
  "Alan Brazil", "Alan Dzagoev", "Alan Kelly", "Alan Kernaghan",
  "Alan McDonald", "Alan McInally", "Alan McLoughlin", "Alan Mullery",
  "Alan Pulido", "Alan Rough", "Alassane N'Dour", "Alberigo Evani",
  "Albert Adomah", "Albert Bunjaku", "Albert Celades", "Albert Ferrer",
  "Albert Luque", "Albert Nađ", "Albert Rust", "Albert Shesternyov",
  "Alberto Aquilani", "Alberto Cardaccio", "Alberto Gallardo", "Alberto García Aspe",
  "Alberto Gilardino", "Alberto Gómez", "Alberto Górriz", "Alberto Medina",
  "Alberto Quintano", "Alberto Rodríguez", "Alberto Tarantini", "Alberto Villalta",
  "Aldair", "Aldo Bobadilla", "Aldo Maldera", "Aldo Poy",
  "Aldo Serena", "Alejandro Bedoya", "Alejandro Domínguez", "Alejandro Lembo",
  "Alejandro Mancuso", "Alekos Alexandris", "Aleksandar Kolarov", "Aleksandar Luković",
  "Aleksandar Markov", "Aleksandar Radosavljević", "Aleksandar Shalamanov", "Aleksander Knavs",
  "Aleksander Šeliga", "Aleksandr Borodyuk", "Aleksandr Bubnov", "Aleksandr Chivadze",
  "Aleksandr Filimonov", "Aleksandr Kerzhakov", "Aleksandr Kokorin", "Aleksandr Mostovoi",
  "Aleksandr Samedov", "Aleksandr Uvarov", "Aleksandr Zavarov", "Aleksei Ionov",
  "Aleksei Kozlov", "Alemão", "Alen Bokšić", "Aleš Čeh",
  "Alessandro Altobelli", "Alessandro Costacurta", "Alessandro dos Santos", "Alessio Cerci",
  "Alex", "Álex Aguinaga", "Alex McLeish", "Alex Oxlade-Chamberlain",
  "Alex Song", "Alex Stepney", "Alex Tachie-Mensah", "Alex Wilkinson",
  "Alexander Domínguez", "Alexander Frei", "Alexander Horváth", "Alexander Mejía",
  "Alexander Vencel", "Alexandre Czerniatynski", "Alexandre Guimarães", "Alexandros Tziolis",
  "Alexandros Tzorvas", "Alexandru Neagu", "Alexey Smertin", "Alexi Lalas",
  "Alexis Alexiou", "Alexis Alexoudis", "Alexis Mendoza", "Alexis Sánchez",
  "Alf-Inge Håland", "Alfons Peeters", "Alfonso", "Alfonso Domínguez",
  "Alfonso Lara", "Alfonso Obregón", "Alfred Hörtnagl", "Alfred Phiri",
  "Alfredo", "Alfredo Mendoza", "Alfredo Quesada", "Alfredo Talavera",
  "Alfredo Tena", "Ali Akbar Ostad-Asadi", "Ali Bencheikh", "Ali Boumnijel",
  "Ali Daei", "Ali El Khattabi", "Ali Fergani", "Ali Hussein Shihab",
  "Ali Kaabi", "Ali Karimi", "Ali Latifi", "Ali Parvin",
  "Ali Reza Ghesghayan", "Ali Shojaei", "Ali Thani Jumaa", "Ali Zitouni",
  "Aliou Cissé", "Alioum Boukar", "Alireza Haghighi", "Alireza Jahanbakhsh",
  "Alireza Mansourian", "Aljoša Asanović", "Allal Ben Kassou", "Allan Boath",
  "Allan Clarke", "Allan Evans", "Allan Maher", "Allan Nielsen",
  "Allan Nyom", "Allan Simonsen", "Alloysius Agu", "Ally McCoist",
  "Alou Diarra", "Alpay Özalan", "Alphonse Tchami", "Alphonse Yombi",
  "Álvaro", "Álvaro Arbeloa", "Álvaro Fernández", "Álvaro González",
  "Álvaro Mesén", "Álvaro Peña", "Álvaro Pereira", "Álvaro Recoba",
  "Álvaro Saborío", "Alvin Martin", "Amado Guevara", "Amara Traoré",
  "Amaral", "Amdy Faye", "Américo Gallego", "Amir Hossein Sadeghi",
  "Amir Karić", "Amor Jebali", "An Chol-Hyok", "Anđelko Đuričić",
  "An Ik-Soo", "An Qi", "An Yong-Hak", "Anad Abid Tweresh",
  "Anatoli Nankov", "Anatoliy Byshovets", "Anatoliy Demyanenko", "Anatoliy Puzach",
  "Anatoliy Tymoshchuk", "Anders Limpar", "Anders Linderoth", "Anders Svensson",
  "Ânderson Polga", "Andoni Goikoetxea", "Andoni Zubizarreta", "Andranik Eskandarian",
  "Andranik Teymourian", "András Törőcsik", "András Tóth", "Andraž Kirm",
  "André", "André Almeida", "André Arendse", "André Ayew",
  "André Cruz", "André Egli", "André Kana-Biyik", "André Ooijer",
  "André-Pierre Gignac", "André Schürrle", "Andrea Barzagli", "Andrea Carnevale",
  "Andreas Andersson", "Andreas Brehme", "Andreas Heraf", "Andreas Herzog",
  "Andreas Isaksson", "Andreas Jakobsson", "Andreas Köpke", "Andreas Möller",
  "Andreas Ogris", "Andreas Reisinger", "Andreas Samaris", "Andrei Piatnitski",
  "Andrei Semyonov", "Andrei Solomatin", "Andrei Zygmantovich", "Andrej Komac",
  "Andrej Kvašňák", "Andrej Panadić", "Andrés Escobar", "Andrés Estrada",
  "Andrés Guardado", "Andrés Scotti", "Andrew Boyens", "Andrew O'Brien",
  "Andrey Yeshchenko", "Andrey Zhelyazkov", "Andriy Bal", "Andriy Husin",
  "Andriy Nesmachnyi", "Andriy Pyatov", "Andriy Rusol", "Andriy Vorobey",
  "Andriy Voronin", "Andrzej Buncol", "Andrzej Fischer", "Andrzej Iwan",
  "Andrzej Pałasz", "Andrzej Szarmach", "Andrzej Zgutczyński", "Andy Barron",
  "Andy Goram", "Andy Najar", "Andy Townsend", "Andy Williams",
  "Anel Hadžić", "Anele Ngcongca", "Ángel Bargas", "Ángel Comizzo",
  "Ángel Fernández", "Angelo Di Livio", "Angelo Domenghini", "Angelo Palombo",
  "Angelo Peruzzi", "Angelos Charisteas", "Anis Ayari", "Antal Nagy",
  "Antal Róth", "Antar Yahia", "Ante Čović", "Ante Rebić",
  "Anthony Annan", "Anthony Costly", "Anthony Réveillère", "Anthony Šerić",
  "Anthony Vanden Borre", "Anthony Wolfe", "Antolín Alcaraz", "Anton Doboş",
  "Anton Flešár", "Anton Pfeffer", "Anton Pichler", "Antonello Cuccureddu",
  "Antoni Szymanowski", "Antonín Kinský", "Antonín Panenka", "Antonio Alzamendi",
  "António André", "Antonio Arias", "Antonio Benarrivo", "Antonio Biosca",
  "Antonio Cabrini", "Antonio Candreva", "Antonio Cassano", "Antonio Conte",
  "Antonio de la Cruz", "Antonio de la Torre", "Antonio Di Gennaro", "Antonio Di Natale",
  "Antonio Guzmán", "Antonio Juliano", "Antonio Laing", "Antonio López",
  "Antonio Maceda", "António Morato", "Antonio Mota", "Antonio Munguía",
  "António Oliveira", "Antonio Olmo", "Antonio Rukavina", "António Sousa",
  "Antonis Minou", "Antony de Ávila", "Anzor Kavazashvili", "Arash Borhani",
  "Archie Gemmill", "Archie Thompson", "Ardian Kozniku", "Arie Haan",
  "Ariel Garcé", "Ariel Ortega", "Arif Erdem", "Aristide Zogbo",
  "Arístides Rojas", "Arkadiusz Bąk", "Arkadiusz Głowacki", "Arkadiusz Radomski",
  "Armando Manzo", "Arne Friedrich", "Arnold Wetl", "Arnoldo Iguarán",
  "Aron Jóhannsson", "Aron Winter", "Arouna Koné", "Arsène Auguste",
  "Artem Milevskyi", "Arthur Albiston", "Arthur Boka", "Arthur Numan",
  "Artur Boruc", "Arturo Vázquez Ayala", "Arturo Vidal", "Aruna Dindane",
  "Asa Hartford", "Ashkan Dejagah", "Ashraf Kasem", "Asmir Avdukić",
  "Asmir Begović", "Asparuh Nikodimov", "Assimiou Touré", "Atanas Mihailov",
  "Atanas Pashev", "Atilio Ancheta", "Atsushi Yanagisawa", "Atsuto Uchida",
  "Attila Abonyi", "Attila Kerekes", "Augustin Deleanu", "Augustine Eguavoen",
  "Augustine Simo", "Augusto Fernández", "Augusto Inácio", "Augusto Porozo",
  "Aureliano Torres", "Aurélien Chedjou", "Aurtis Whitley", "Austin Ejide",
  "Avdija Vršajević", "Avery John", "Avraam Papadopoulos", "Awad Al-Anazi",
  "Axel Witsel", "Ayan Sadakov", "Ayila Yussuf", "Ayman Shawky",
  "Ayman Taher", "Aziz Bouderbala", "Azubuike Egwuekwe", "Azzedine Amanallah",
  "Bacary Sagna", "Badou Zaki", "Baek Ji-Hoon", "Bahram Mavaddat",
  "Bailey Wright", "Bakari Koné", "Bakhtiar Rahmani", "Baldocchi",
  "Barry Pickering", "Bart Goor", "Bartholomew Ogbeche", "Bartosz Bosacki",
  "Basarab Panduru", "Basil Gorgis Hanna", "Basim Qasim Hamdan", "Bassey William Andem",
  "Batista", "Baudilio Jáuregui", "Bebeto", "Behnam Seraj",
  "Behtash Fariba", "Béla Bodonyi", "Béla Katzirz", "Béla Várady",
  "Ben Foster", "Ben Halloran", "Ben Olsen", "Ben Sigmund",
  "Benedict Akwuegbu", "Benedict Iroha", "Benedikt Höwedes", "Benjamin Angoua",
  "Benjamín Galindo", "Benjamin Huggel", "Benjamin Massing", "Benjamin Moukandjo",
  "Bennett Mnguni", "Benni McCarthy", "Benno Magnusson", "Benny Feilhaber",
  "Benny Wendt", "Benoît Assou-Ekotto", "Bernard", "Bernard Dietz",
  "Bernard Diomède", "Bernard Genghini", "Bernard Lacombe", "Bernard Lama",
  "Bernard McNally", "Bernard Parker", "Bernardo Redín", "Bernd Bransch",
  "Bernd Förster", "Bernd Franke", "Bernd Hölzenbein", "Bernd Krauss",
  "Bernd Patzke", "Bernd Schneider", "Bernd Thijs", "Bernhard Cullmann",
  "Bernie Slaven", "Berry van Aerle", "Berti Vogts", "Bertin Ebwellé",
  "Bertrand Crasson", "Beto", "Bill Tchato", "Billy Bremner",
  "Billy Hamilton", "Billy McClure", "Billy McKinlay", "Bismarck",
  "Bixente Lizarazu", "Bjarne Goldbæk", "Björn Andersson", "Björn Nordqvist",
  "Blaise Kouassi", "Blaise Matuidi", "Blaise Nkufo", "Blerim Džemaili",
  "Bo Larsson", "Bob Lenarduzzi", "Bobby Almond", "Bobby Campbell",
  "Bobby Charlton", "Bobby Clark", "Bobby Convey", "Bobby Moore",
  "Bodo Illgner", "Bogdan Stelea", "Bohdan Masztaler", "Bohdan Shust",
  "Bohumil Veselý", "Bojan Isailović", "Bojan Jokić", "Bonaventure Djonkep",
  "Bonaventure Kalou", "Boncho Genchev", "Bongani Khumalo", "Boris Gaganelov",
  "Boris Živković", "Borislav Mikhailov", "Boško Balaban", "Boštjan Cesar",
  "Boubacar Barry", "Boudewijn Zenden", "Boujemaa Benkhrif", "Boycho Velichkov",
  "Bozhidar Grigorov", "Bozhidar Iskrenov", "Bozhil Kolev", "Brad Davis",
  "Brad Friedel", "Brad Guzan", "Bradley Carnell", "Branco",
  "Branislav Ivanović", "Branko Brnović", "Branko Buljevic", "Branko Ilič",
  "Branko Oblak", "Branko Segota", "Branko Strupar", "Braulio Luna",
  "Brayan Beckeles", "Brendan Augustine", "Brent Sancho", "Brett Emerton",
  "Brett Holman", "Brian Baloyi", "Brian Bliss", "Brian Ching",
  "Brian Labone", "Brian Laudrup", "Brian Maisonneuve", "Brian McBride",
  "Brian Steen Nielsen", "Brian Turner", "Brito", "Brown Ideye",
  "Bruce Murray", "Bruce Rioch", "Bruce Wilson", "Bruno Alves",
  "Bruno Bellone", "Bruno Conti", "Bruno Martins Indi", "Bruno Pezzey",
  "Bruno Versavel", "Bryan Roy", "Bryan Ruiz", "Buenaventura Ferreira",
  "Bülent Korkmaz", "Bwanga Tshimen", "Byun Byung-Joo", "Cacau",
  "Calvin Marlin", "Camilo Vargas", "Capucho", "Careca",
  "Carl Medjani", "Carl Valentine", "Carl Valeri", "Carles Rexach",
  "Carlo Ancelotti", "Carlo Costly", "Carlos", "Carlos Aguilera",
  "Carlos Alberto", "Carlos Babington", "Carlos Bacca", "Carlos Bocanegra",
  "Carlos Bonet", "Carlos Borja", "Carlos Caballero", "Carlos Carbonero",
  "Carlos Carmona", "Carlos Castro", "Carlos Caszely", "Carlos de los Cobos",
  "Carlos Edwards", "Carlos Estrada", "Carlos Gamarra", "Carlos Germano",
  "Carlos Gómez", "Carlos Gruezo", "Carlos Hermosillo", "Carlos Hernández",
  "Carlos Hoyos", "Carlos Kameni", "Carlos Llamosa", "Carlos Manuel",
  "Carlos Marchena", "Carlos Morales", "Carlos Mozer", "Carlos Muñoz",
  "Carlos Paredes", "Carlos Pavón", "Carlos Peña", "Carlos Recinos",
  "Carlos Reinoso", "Carlos Rivas", "Carlos Roa", "Carlos Salcido",
  "Carlos Sánchez", "Carlos Squeo", "Carlos Tapia", "Carlos Tejas",
  "Carlos Tenorio", "Carlos Trucco", "Carlos Valderrama", "Carlos Valdés",
  "Carlos Vela", "Carpegiani", "Carsten Jancker", "Carsten Ramelow",
  "Casagrande", "Catalino Rivarola", "Cédric Carrasso", "Cédric Djeugoué",
  "Cédric Si Mohamed", "Celestine Babayaro", "Celso Ayala", "Celso Borges",
  "Celso Güity", "Celso Otero", "César", "César Cueto",
  "César Ramírez", "César Sampaio", "César Vega", "César Zabala",
  "Cezary Kucharski", "Cha Bum-Kun", "Cha Du-Ri", "Cha Jong-Hyok",
  "Chaabane Merzekane", "Chad Deering", "Chaouki Ben Saada", "Charles Aránguiz",
  "Charles Itandje", "Charles Toubé", "Charlie Nicholas", "Cheick Tioté",
  "Chendo", "Chicão", "Chidi Nwanu", "Chidi Odiah",
  "Chigozie Agbim", "Chinedu Obasi", "Cho Byung-Deouk", "Cho Jae-Jin",
  "Cho Jin-Ho", "Cho Kwang-Rae", "Cho Min-Kook", "Cho Won-Hee",
  "Cho Yong-Hyung", "Cho Young-Jeung", "Choe Kum-Chol", "Choi Dae-Shik",
  "Choi Eun-Sung", "Choi In-Young", "Choi Jin-Cheul", "Choi Kang-Hee",
  "Choi Moon-Sik", "Choi Soon-Ho", "Choi Sung-Yong", "Choi Tae-Uk",
  "Choi Yong-Soo", "Choi Young-Il", "Chokri El Ouaer", "Chris Albright",
  "Chris Birchall", "Chris Dawes", "Chris Henderson", "Chris Hughton",
  "Chris Killen", "Chris Morris", "Chris Nicholl", "Chris Smalling",
  "Chris Wondolowski", "Chris Wood", "Chris Woods", "Christian Abbiati",
  "Christian Atsu", "Christian Benítez", "Christian Bolaños", "Christian Dailly",
  "Christian Dalger", "Christian Eriksen", "Christian Karembeu", "Christian Keglevits",
  "Christian Lara", "Christian Lopez", "Christian Maggio", "Christian Noboa",
  "Christian Panucci", "Christian Piot", "Christian Poulsen", "Christian Stuani",
  "Christian Vieri", "Christian Wilhelmsson", "Christian Wörns", "Christian Ziege",
  "Christoph Kramer", "Christoph Metzelder", "Christoph Spycher", "Christophe Dugarry",
  "Christophe Ohrel", "Christopher Sullivan", "Christos Karkamanis", "Christos Patsatzoglou",
  "Chung Hae-Won", "Chung Jong-Son", "Chung Jong-Soo", "Chung Kyung-Ho",
  "Chung Yong-Hwan", "Cicinho", "Ciriaco Sforza", "Ciro Ferrara",
  "Ciro Immobile", "Claes Cronqvist", "Clarence Acuña", "Clarence Goodson",
  "Claude Barthélemy", "Claude Papi", "Claudio Borghi", "Claudio Bravo",
  "Claudio Caniggia", "Claudio Gentile", "Claudio Husaín", "Claudio Jara",
  "Claudio López", "Claudio Marchisio", "Claudio Morel", "Claudio Reyna",
  "Claudio Sala", "Claudio Suárez", "Claus Jensen", "Clayton Ince",
  "Cle Kooiman", "Cléber Chalá", "Clemente Rodríguez", "Clint Dempsey",
  "Clint Mathis", "Clinton Morrison", "Clodoaldo", "Cobi Jones",
  "Colin Bell", "Colin Calderwood", "Colin Clarke", "Colin Curran",
  "Colin Hendry", "Colin Miller", "Collin Samuel", "Comunardo Niccolai",
  "Conny Torstensson", "Constant Djakpa", "Constantin Gâlcă", "Cornel Dinu",
  "Corneliu Papură", "Cornell Glen", "Costinha", "Craig Burley",
  "Craig Levein", "Craig Moore", "Cris", "Cristián Castañeda",
  "Cristian Dulca", "Cristian Gamboa", "Cristian Mora", "Cristian Riveros",
  "Cristian Rodríguez", "Cristian Zaccardo", "Cristián Zapata", "Cristiano Doni",
  "Cristiano Zanetti", "Cristóbal Ortega", "Cristopher Toselli", "Cuauhtémoc Blanco",
  "Curro Torres", "Cyd Gray", "Cyril Domoraud", "Cyril Nzama",
  "Cyrille Makanaky", "Dado Pršo", "Dagoberto Fontes", "Daiki Iwamasa",
  "Daisuke Ichikawa", "Daisuke Matsui", "Dale Mitchell", "Daley Blind",
  "Dalibor Stevanovič", "DaMarcus Beasley", "Damián Lanza", "Damiano Tommasi",
  "Damien Duff", "Dan Coe", "Dan Eggen", "Dan Petrescu",
  "Dani", "Dani Shmulevich-Rom", "Daniel Adjei", "Daniel Agger",
  "Daniel Alves", "Daniel Amokachi", "Daniel Andersson", "Daniel Bertoni",
  "Daniel Borimirov", "Daniel Cambronero", "Daniel Carnevali", "Daniel Davari",
  "Daniel Fernandes", "Daniel Fonseca", "Daniel Gygax", "Daniel Jensen",
  "Daniel Killer", "Daniel N'Gom Kome", "Daniel Opare", "Daniel Passarella",
  "Daniel Prodan", "Daniel Quaye", "Daniel Revelez", "Daniel Sanabria",
  "Daniel Šarić", "Daniel Sturridge", "Daniel Timofte", "Daniel Vallejos",
  "Daniel Van Buyten", "Daniel Veyt", "Daniel Viteri", "Daniel Xuereb",
  "Daniel Yeboah", "Daniele Massaro", "Danijel Ljuboja", "Danijel Pranjić",
  "Danijel Subašić", "Danilo Aceval", "Danilo Popivoda", "Danilo Turcios",
  "Danko Lazović", "Danny", "Danny Blind", "Danny Boffin",
  "Danny Fonseca", "Danny McGrain", "Danny Mills", "Danny Shittu",
  "Danny Welbeck", "Dante", "Dante López", "Dănuţ Lupu",
  "Dany Nounkeu", "Dany Verlinden", "Daré Nibombé", "Darijo Srna",
  "Dario", "Darío Pereyra", "Darío Rodríguez", "Darío Rojas",
  "Darío Silva", "Dario Šimić", "Darío Verón", "Dario Vidošić",
  "Dariusz Dudka", "Dariusz Dziekanowski", "Dariusz Kubicki", "Darko Kovačević",
  "Darko Pančev", "Darren Anderton", "Darren Jackson", "Darryl Powell",
  "Daryl Janmaat", "Dave Bright", "Dave Harding", "David Albelda",
  "David Atiba Charles", "David Batty", "David Buezo", "David Cabrera",
  "David Campbell", "David Carney", "David Connolly", "David de Gea",
  "David Degen", "David Embé", "David Harvey", "David Hay",
  "David Jarolím", "David Jemmali", "David Karako", "David Kelly",
  "David Luiz", "David McCreery", "David McPherson", "David Mulligan",
  "David Narey", "David Norman", "David Nyathi", "David O'Leary",
  "David Odonkor", "David Ospina", "David Primo", "David Regis",
  "David Rozehnal", "David Suazo", "David Vanole", "David Weir",
  "Davie Cooper", "Davie Provan", "Davor Jozić", "Davor Vugrinec",
  "Dean Kiely", "Dean Sewell", "DeAndre Yedlin", "Deco",
  "Dejan Govedarica", "Dejan Lovren", "Dejan Nemec", "Dejan Savićević",
  "Dejan Stanković", "Dele Adeleye", "Dele Aiyenugba", "Delgado",
  "Delio Toledo", "Delron Buckley", "Demetrio Albertini", "Demy de Zeeuw",
  "Denílson", "Denis Caniza", "Denis Glushakov", "Denis Irwin",
  "Denis Law", "Denis Milar", "Dennis Aogo", "Dennis Lawrence",
  "Dennis Rommedahl", "Denny Landzaat", "Densill Theobald", "Deon Burton",
  "Derek Boateng", "Derek Johnstone", "Derek Whyte", "Derlis Gómez",
  "Desmond Armstrong", "Diamantino", "Dick Nanninga", "Dick Schoenaker",
  "Dickson Etuhu", "Didier Angibeaud", "Didier Deschamps", "Didier Six",
  "Didier Ya Konan", "Didier Zokora", "Diego Barreto", "Diego Benaglio",
  "Diego Calvo", "Diego Forlán", "Diego Gavilán", "Diego Godín",
  "Diego Lugano", "Diego Milito", "Diego Pérez", "Diego Placente",
  "Diego Pozo", "Diego Reyes", "Diego Simeone", "Diego Tristán",
  "Dieter Burdenski", "Dieter Herzog", "Dieter Hoeneß", "Dieter Müller",
  "Dietmar Hamann", "Dietmar Kühbauer", "Dimitar Marashliev", "Dimitar Penev",
  "Dimitar Yakimov", "Dimitris Salpingidis", "Dimitris Saravakos", "Dinko Dermendzhiev",
  "Dino Baggio", "Dino Zoff", "Dirceu", "Dirk Kuyt",
  "Dirk Medved", "Ditmar Jakobs", "Divock Origi", "Djamel Abdoun",
  "Djamel Menad", "Djamel Mesbah", "Djamel Tlemçani", "Djamel Zidane",
  "Djibril Cissé", "Dmitri Alenichev", "Dmitri Galiamin", "Dmitri Kharine",
  "Dmitri Khlestov", "Dmitri Khokhlov", "Dmitri Kombarov", "Dmitri Kuznetsov",
  "Dmitri Popov", "Dmitri Radchenko", "Dmitri Sennikov", "Dmitri Sychev",
  "Dmytro Chyhrynskyi", "Dobromir Zhechev", "Doctor Khumalo", "Domagoj Vida",
  "Domenico Criscito", "Domingo Droumond", "Dominic Adiyiah", "Dominique Baratelli",
  "Dominique Bathenay", "Dominique Dropsy", "Dominique Herr", "Dominique Rocheteau",
  "Don Masson", "Donald Ford", "Doni", "Donis Escober",
  "Donovan Ricketts", "Dorin Mateuţ", "Dorinel Munteanu", "Doriva",
  "Doug Utjesenovic", "Douglas Sequeira", "Dragan Džajić", "Dragan Mrđa",
  "Dragan Pantelić", "Dragan Stojković", "Dragoje Leković", "Dragoljub Brnović",
  "Dragoslav Jevrić", "Dražen Ladić", "Dražen Mužinić", "Dries Mertens",
  "Driss Bamous", "Driss Benzekri", "Du Wei", "Duda",
  "Duilio Davino", "Dumitru Stângaciu", "Duncan Cole", "Dunga",
  "Durrant Brown", "Dušan Bajević", "Dušan Basta", "Dušan Kuciak",
  "Dušan Perniš", "Dušan Petković", "Džoni Novak", "Eamonn Bannon",
  "Earnie Stewart", "Ebbe Sand", "Eberhard Vogel", "Ebrahim Ghasempour",
  "Ebrahim Mirzapour", "Ed de Goeij", "Edder Delgado", "Eddie Johnson",
  "Eddie Lewis", "Eddie McGoldrick", "Eddie Pope", "Eddy Antoine",
  "Eddy Treijtel", "Éder", "Éder Álvarez Balanta", "Edevaldo",
  "Edgar Aguilera", "Edgar Álvarez", "Edgar Barreto", "Édgar Benítez",
  "Edgar Salli", "Edgardo Bauza", "Edhem Šljivo", "Edílson",
  "Edin Džeko", "Edin Višća", "Edinho", "Edinson Cavani",
  "Edison Méndez", "Edivaldo", "Edmílson", "Edmond Enoka",
  "Edmundo", "Édson", "Edson Braafheid", "Edson Buddle",
  "Edu", "Eduard Krieger", "Eduardo", "Eduardo Bonvallet",
  "Eduardo Hernández", "Eduardo Malásquez", "Eduardo Mario Acevedo", "Eduardo Niño",
  "Eduardo Pereira", "Eduardo Ramos", "Eduardo Vargas", "Edwin Tenorio",
  "Edwin Villafuerte", "Efan Ekoku", "Efe Ambrose", "Efe Sodje",
  "Efraín Gutiérrez", "Efraín Juárez", "Egidio Arévalo Ríos", "Egil Østenstad",
  "Ehsan Hajsafi", "Eiji Kawashima", "Eike Immel", "Eissa Meer",
  "Eisuke Nakanishi", "El Arbi Hababi", "El Arbi Hillel Soudani", "El Hadji Diouf",
  "Eladio Reyes", "Elano", "Eli Ben Rimoz", "Eliaquim Mangala",
  "Elias Atmatsidis", "Elías Figueroa", "Elie Onana", "Eliseo Rivero",
  "Eljero Elia", "Elmer Acevedo", "Eloy", "Eloy Campos",
  "Elvedin Džinić", "Elzo", "Emeka Ezeugo", "Emerich Dembrovschi",
  "Emerse Faé", "Emerson", "Emil Kostadinov", "Emil Kremenliev",
  "Emil Săndoi", "Emile M'Bouh", "Émile Mpenza", "Emilio Butragueño",
  "Emilio Izaguirre", "Emir Mkademi", "Emir Spahić", "Emlyn Hughes",
  "Emmanuel Adebayor", "Emmanuel Agyemang-Badu", "Emmanuel Amuneke", "Emmanuel Eboué",
  "Emmanuel Emenike", "Emmanuel Koné", "Emmanuel Kundé", "Emmanuel Maboang",
  "Emmanuel Olisadebe", "Emmanuel Pappoe", "Emmanuel Sanon", "Emre Aşık",
  "Emre Belözoğlu", "Enner Valencia", "Enrico Albertosi", "Enrico Chiesa",
  "Enrique Borja", "Enrique Chazarreta", "Enrique López Zarza", "Enrique Romero",
  "Enrique Saura", "Enrique Vera", "Enrique Wolff", "Enver Hadžiabdić",
  "Enver Marić", "Enzo Escobar", "Enzo Francescoli", "Enzo Pérez",
  "Enzo Scifo", "Enzo Trossero", "Ephrem M'Bom", "Eraldo Pecci",
  "Eren Derdiyok", "Ergün Penbe", "Éric Abidal", "Eric Addo",
  "Éric Akoto", "Eric Choupo-Moting", "Eric Deflandre", "Eric Djemba-Djemba",
  "Eric Eichmann", "Eric Ejiofor", "Eric Gerets", "Eric Van Meir",
  "Eric Wynalda", "Erich Beer", "Erich Hamann", "Erich Obermayer",
  "Erich Schaedler", "Erick Lonnis", "Erik Durm", "Erik Edman",
  "Erik Hoftun", "Erik Jendrišek", "Erik Mykland", "Erik Thorstvedt",
  "Erland Johnsen", "Ermin Bičakčić", "Ernest Ebongué", "Ernesto Aparicio",
  "Ernesto Labarthe", "Ernie Brandts", "Ernie Campbell", "Ernst Aigner",
  "Ernst Baumeister", "Ernst Jean-Joseph", "Erwin Fuchsbichler", "Erwin Koeman",
  "Erwin Sánchez", "Erwin Vandenbergh", "Erwin Vandendaele", "Espen Baardsen",
  "Essaïd Belkalem", "Estanislao Struway", "Esteban Granados", "Esteban Paredes",
  "Eufemio Cabral", "Eugène Ekéké", "Eugene Galeković", "Eugenio Leal",
  "Eugenio Mena", "Eusebio Acasuzo", "Euzebiusz Smolarek", "Evans Wise",
  "Evaristo Isasi", "Ever Hernández", "Ever Palacios", "Everaldo",
  "Evgeny Lovchev", "Eyong Enoh", "Ezequiel Garay", "Ezequiel Lavezzi",
  "Fabián Cancelarich", "Fabián Carini", "Fabián Estay", "Fabian Johnson",
  "Fabián O'Neill", "Fabián Orellana", "Fabian Schär", "Fabio Capello",
  "Fábio Coentrão", "Fabio Coltorti", "Fabio Grosso", "Fabio Quagliarella",
  "Fabrice Olinga", "Fabricio Coloccini", "Fabrizio Poletti", "Fadel Jilal",
  "Fahad Abdulrahman", "Fahad Al-Bishi", "Fahad Al-Ghesheyan", "Fahad Al-Mehallel",
  "Fahad Khamees", "Fahrudin Omerović", "Faisal Al-Dakhil", "Falcão",
  "Fan Zhiyi", "Faouzi Chaouchi", "Faouzi Ghoulam", "Faouzi Mansouri",
  "Farid Mondragón", "Faruk Hadžibegić", "Faryd Mondragón", "Fatau Dauda",
  "Fathi Chebal", "Fathi Kameel", "Fatih Akyel", "Faustino Alonso",
  "Faustino Asprilla", "Fawzi Benkhalidi", "Faysal Ben Ahmed", "Federico Elduayen",
  "Federico Fernández", "Federico Magallanes", "Federico Marchetti", "Felipe Caicedo",
  "Felipe Gutiérrez", "Felipe Melo", "Felipe Miñambres", "Félix",
  "Félix Borja", "Felix Cruz", "Félix Fernández", "Felix Healy",
  "Felix Magath", "Félix Salinas", "Femi Opabunmi", "Ferdinand Coly",
  "Ferenc Csongrádi", "Ferenc Fülöp", "Ferenc Mészáros", "Ferid Chouchane",
  "Fernandinho", "Fernando", "Fernando Alvez", "Fernando Bulnes",
  "Fernando Cáceres", "Fernando Clavijo", "Fernando Cornejo", "Fernando Couto",
  "Fernando De Napoli", "Fernando Gago", "Fernando Gomes", "Fernando Llorente",
  "Fernando Meira", "Fernando Morena", "Fernando Morientes", "Fernando Muslera",
  "Fernando Óscar Bandeirinha", "Fernando Quirarte", "Fernando Redondo", "Ferydoon Zandi",
  "Fidel Martínez", "Figueiredo", "Filip De Wilde", "Filip Hološko",
  "Finidi George", "Fitzroy Simpson", "Flávio", "Flavius Domide",
  "Flemming Christensen", "Florea Dumitrache", "Florent Malouda", "Florin Prunea",
  "Florin Răducioiu", "Fodil Megharia", "Fontana", "Foued Kadir",
  "Fouzi Al-Shehri", "Francesco Coco", "Francesco Graziani", "Francesco Moriero",
  "Francesco Morini", "Francesco Toldo", "Francileudo Santos", "Francis Lee",
  "Francisco", "Francisco Alcaraz", "Francisco Arce", "Francisco Cámera",
  "Francisco Castrejón", "Francisco Fonseca", "Francisco Gabriel de Anda", "Francisco Javier Cruz",
  "Francisco Javier Rodríguez", "Francisco Javier Toledo", "Francisco Javier Uría", "Francisco José Camarasa",
  "Francisco José Carrasco", "Francisco Montes", "Francisco Osorto", "Francisco Palencia",
  "Francisco Rodríguez", "Francisco Rojas", "Francisco Sá", "Francisco Silva",
  "Francisco Valdés", "Francisco Villarroya", "Franck Atsou", "Franco Baresi",
  "Franco Causio", "Franco Navarro", "Franco Selvaggi", "Franco Tancredi",
  "François Bracci", "François N'Doumbé", "François Omam-Biyik", "François Van Der Elst",
  "Franjo Vladić", "Frank Arnesen", "Frank Baumann", "Frank de Boer",
  "Frank Gray", "Frank Klopas", "Frank Lebœuf", "Frank Leboeuf",
  "Frank McAvennie", "Frank Mill", "Frank Rijkaard", "Frank Sinclair",
  "Frank Stapleton", "Frank van Hattum", "Frankie Hejduk", "Franky Van Der Elst",
  "Franky Vandendriessche", "Franky Vercauteren", "Frans Janssens", "František Jakubec",
  "František Štambachr", "František Straka", "František Veselý", "Franz Beckenbauer",
  "Franz Oberacher", "Franz Wohlfahrt", "Fraser Forster", "Fred",
  "Freddy Rincón", "Frédéric Herpoel", "Frederico", "Fredrik Ljungberg",
  "Fredrik Stenman", "Fredy Guarín", "Frickson Erazo", "Friedrich Koncilia",
  "Fritz André", "Fritz Leandré", "Frode Grodås", "Fuad Amin",
  "Fulvio Collovati", "Gøran Sørloth", "Gábor Pölöskei", "Gabriel Achilier",
  "Gabriel Badilla", "Gabriel Caballero", "Gabriel Calderón", "Gabriel Correa",
  "Gabriel Gómez", "Gabriel Heinze", "Gabriel Milito", "Gabriel Paletta",
  "Gabriel Popescu", "Gabriele Oriali", "Gaël Clichy", "Gaël Givet",
  "Gaëtan Bong", "Gaëtan Englebert", "Gaetano Scirea", "Gaizka Mendieta",
  "Gamal Abdelhamid", "Gao Yao", "Garba Lawal", "Gareth Barry",
  "Gary A. Stevens", "Gary Bailey", "Gary Breen", "Gary Gillespie",
  "Gary Kelly", "Gary Manuel", "Gary McAllister", "Gary Medel",
  "Gary Stevens", "Gastón Ramírez", "Gaston Taument", "Gavril Balint",
  "Geert De Vlieger", "Gelson Fernandes", "Genar Andrinúa", "Genaro Sarmeno",
  "Gennadiy Litovchenko", "Gennadiy Lytovchenko", "Gennady Logofet", "Gennady Morozov",
  "Gennady Yevriuzhikin", "Geoff Cameron", "Geoff Hurst", "George Borba",
  "George Burley", "George Dunlop", "George Koumantarakis", "George Owu",
  "George Pakos", "George Wood", "Georges Bregy", "Georges Grün",
  "Georges Heylens", "Georges Mandjeck", "Georges Mouyémé", "Georgi Asparuhov",
  "Georgi Bachev", "Georgi Denev", "Georgi Dimitrov", "Georgi Georgiev",
  "Georgi Ivanov", "Georgi Kamenski", "Georgi Popov", "Georgi Shchennikov",
  "Georgi Yordanov", "Georgie Welcome", "Georgios Samaras", "Geovanis Cassiani",
  "Geovanny Jara", "Gerald Asamoah", "Gerald Glatzmayer", "Gerald Messlender",
  "Gerald Vanenburg", "Gérard Gnanhouan", "Gérard Janvion", "Gérard Joseph",
  "Gerard Plessers", "Gérard Soler", "Gerardo Lugo", "Gerardo Torrado",
  "Gerd Kische", "Gerd Müller", "Gerd Zewe", "Geremi",
  "Geremi Njitap", "Gerhard Breitenberger", "Gerhard Rodax", "Germán Burgos",
  "Germán Chavarría", "Germán Leguía", "Germán Villa", "Gernot Jurtin",
  "Gerónimo Barbadillo", "Gerry Armstrong", "Gerry Gray", "Gerry Peyton",
  "Gérson", "Gert Verheyen", "Gervinho", "Ghafour Jahani",
  "Ghanim Oraibi Jassim", "Gharib Amzine", "Ghasem Haddadifar", "Gheorghe Craioveanu",
  "Gheorghe Gornea", "Gheorghe Hagi", "Gheorghe Liliac", "Gheorghe Mihali",
  "Gheorghe Popescu", "Gheorghe Tătaru", "Giacinto Facchetti", "Giampaolo Pazzini",
  "Giampiero Marini", "Giancarlo Antognoni", "Giancarlo De Sisti", "Giancarlo González",
  "Giancarlo Marocchi", "Gianfranco Zola", "Gianluca Pagliuca", "Gianluca Pessotto",
  "Gianluca Vialli", "Gianluca Zambrotta", "Gianni Guigou", "Gianni Rivera",
  "Giannis Fetfatzidis", "Giannis Maniatis", "Gil", "Gilbert Bodart",
  "Gilberto", "Gilberto Martínez", "Gilberto Silva", "Gilberto Yearwood",
  "Gildardo Gómez", "Gilles Yapi Yapo", "Gilmar", "Giora Spiegel",
  "Giorgio Chinaglia", "Giorgio Puia", "Giorgos Karagounis", "Giorgos Samaras",
  "Giorgos Tzavellas", "Giotis Tsalouchidis", "Giourkas Seitaridis", "Giovani dos Santos",
  "Giovanni", "Giovanni Galli", "Giovanni Sio", "Giovanni van Bronckhorst",
  "Giovanny Espinoza", "Giuseppe Baresi", "Giuseppe Bergomi", "Giuseppe Dossena",
  "Giuseppe Furino", "Giuseppe Galderisi", "Giuseppe Giannini", "Giuseppe Sabadini",
  "Giuseppe Signori", "Giuseppe Wilson", "Givi Nodia", "Glen Adam",
  "Glen De Boeck", "Glen Johnson", "Glen Moss", "Glenn Dods",
  "Glenn Hoddle", "Glenn Hysén", "Glenn Strömberg", "Godfrey Oboabona",
  "Godwin Okpara", "Gojko Kačar", "Gökhan Inler", "Gomes",
  "Gonçalves", "Gonzalo de los Santos", "Gonzalo Fierro", "Gonzalo Jara",
  "Gonzalo Pineda", "Gonzalo Sorondo", "Goran Đorović", "Goran Gavrančić",
  "Göran Hagberg", "Goran Jurić", "Göran Nicklasson", "Goran Sankovič",
  "Goran Vlaović", "Gordan Vidović", "Gordon Banks", "Gordon Durie",
  "Gordon McQueen", "Gordon Schildenfeld", "Gordon Strachan", "Gosho Ginchev",
  "Gōtoku Sakai", "Graeme Le Saux", "Graeme Rutjes", "Graeme Sharp",
  "Grafite", "Graham Rix", "Graham Zusi", "Granit Xhaka",
  "Grant Turner", "Greg Ion", "Gregg Berhalter", "Grégoire M'Bida",
  "Grégory Coupet", "Gregory van der Wiel", "Grzegorz Lato", "Grzegorz Rasiak",
  "Gu Sang-Bum", "Gualberto Fernández", "Guido Alvarenga", "Guido Buchwald",
  "Guillermo Amor", "Guillermo Castro", "Guillermo Franco", "Guillermo Hernández",
  "Guillermo La Rosa", "Guillermo Mendizábal", "Guillermo Ochoa", "Guillermo Páez",
  "Guillermo Ragazzone", "Guillermo Yávar", "Gunnar Halle", "Günter Hermann",
  "Günter Netzer", "Günther Happich", "Gustavo de Simone", "Gustavo Dezotti",
  "Gustavo Fernández", "Gustavo López", "Gustavo Méndez", "Gustavo Morínigo",
  "Gustavo Moscoso", "Gustavo Munúa", "Gustavo Peña", "Gustavo Quinteros",
  "Gustavo Varela", "Guy Demel", "Guy François", "Guy N'dy Assembé",
  "Guy Saint-Vil", "Guy Vandersmissen", "György Bognár", "Győző Burcsa",
  "Győző Martos", "Gyula Hajszán", "Ha Dae-Sung", "Ha Seok-Ju",
  "Habib Bellaïd", "Habib Beye", "Habib Mohamed", "Håkan Mild",
  "Hakan Şükür", "Hakan Ünsal", "Hakan Yakın", "Hakan Yakin",
  "Halim Benmabrouk", "Hamad Al-Montashari", "Hamdi Kasraoui", "Hamdi Marzouki",
  "Hamed Dahane", "Hamed Namouchi", "Hamid Estili", "Hamid Majd Teymouri",
  "Hamilton Ricard", "Haminu Dramani", "Hamoud Al-Shemmari", "Hamzah Idris",
  "Hamzah Saleh", "Han Kook-Young", "Hannes Löhr", "Hannes Reinmayr",
  "Hans Agbo", "Hans-Georg Schwarzenbeck", "Hans Gillhaus", "Hans-Jörg Butt",
  "Hans-Jürgen Kreische", "Hans Krankl", "Hans-Peter Briegel", "Hans Pflügler",
  "Hans Pirkner", "Hans Sarpei", "Hans Selander", "Hans van Breukelen",
  "Hans Vonk", "Hansi Müller", "Hany Ramzy", "Hao Haidong",
  "Harald Cerny", "Harald Irmscher", "Harald Konopka", "Harald Schumacher",
  "Haris Medunjanin", "Haris Mohammed Hassan", "Haris Seferović", "Harold Wallace",
  "Harrison Afful", "Harry Kewell", "Harry Lubse", "Harry Vos",
  "Harry Williams", "Hasan Şaş", "Hashem Beikzadeh", "Hassan Kachloul",
  "Hassan Mohamed", "Hassan Nader", "Hassan Nayebagha", "Hassan Nazari",
  "Hassan Roshan", "Hassan Roudbarian", "Hassan Yebda", "Hasse Borg",
  "Hassen Bejaoui", "Hassen Gabsi", "Hatem Trabelsi", "Håvard Flo",
  "Haykel Guemamdia", "Héctor Baley", "Héctor Chumpitaz", "Héctor Enrique",
  "Héctor Herrera", "Héctor Marchena", "Héctor Moreno", "Héctor Pulido",
  "Héctor Santos", "Héctor Yazalde", "Héctor Zelada", "Héctor Zelaya",
  "Hedwiges Maduro", "Heimo Pfeifenberger", "Heiner Mora", "Heinrich Strasser",
  "Heinz Flohe", "Hélder Postiga", "Helman Mkhalele", "Helmut Haller",
  "Helmut Kremers", "Hendry Thomas", "Henk Fräser", "Henk Timmer",
  "Henning Berg", "Henri Bedimo", "Henri Camara", "Henri Françillon",
  "Henri Michel", "Henrik Andersen", "Henrique", "Henryk Kasperczak",
  "Henryk Maculewicz", "Henryk Wieczorek", "Herbert Feurer", "Herbert Prohaska",
  "Herbert Wimmer", "Herbert Zimmermann", "Herculez Gomez", "Heribert Weber",
  "Hermidio Barrantes", "Hernán Díaz", "Hernán Gaviria", "Hernán Medford",
  "Hernanes", "Hesham Yakan", "Hipólito Rincón", "Hiroaki Morishima",
  "Hiroki Sakai", "Hiroshi Kiyotake", "Hiroshi Nanami", "Hitoshi Sogahata",
  "Hocine Yahi", "Holger Badstuber", "Holger Hieronymus", "Hong Jeong-Ho",
  "Hong Myung-Bo", "Hong Yong-Jo", "Horacio López Salgado", "Horst-Dieter Höttges",
  "Horst Hrubesch", "Horst Wolter", "Hossam Hassan", "Hossein Faraki",
  "Hossein Kaebi", "Hossein Kazerani", "Hossein Mahini", "Hotaru Yamaguchi",
  "Houmane Jarir", "Hristo Bonev", "Hristo Kolev", "Hubert Baumgartner",
  "Hugo Almeida", "Hugo Brizuela", "Hugo Broos", "Hugo Campagnaro",
  "Hugo de León", "Hugo Gastulo", "Hugo Hovenkamp", "Hugo Perez",
  "Hugo René Rodríguez", "Hugo Sánchez", "Hugo Sotil", "Hugo Viana",
  "Huh Jung-Moo", "Hulk", "Humberto Suazo", "Hussain Ghuloum",
  "Hussein Al-Sadiq", "Hussein Saeed Mohammed", "Hussein Sulaimani", "Hwang Seok-Ho",
  "Hwang Sun-Hong", "Hwangbo Kwan", "Hyun Young-Min", "Ian Bridge",
  "Ian Cox", "Ian Goodison", "Ian Harte", "Ian Stewart",
  "Ibrahim Afellay", "Ibrahim Al-Harbi", "Ibrahim Al-Helwah", "Ibrahim Al-Shahrani",
  "Ibrahim Aoudou", "Ibrahim Hassan", "Ibrahim Meer", "Idriss Carlos Kameni",
  "Ifeanyi Udeze", "Ignacio Ambríz", "Ignacio Calderón", "Ignacio Flores Ocaranza",
  "Ignacio González", "Ignacio Rodríguez", "Ignazio Abate", "Igor Akinfeev",
  "Igor Chugainov", "Igor Denisov", "Igor Dobrovolski", "Igor Duljaj",
  "Igor Korneev", "Igor Lediakhov", "Igor Semshov", "Igor Shalimov",
  "Igor Štimac", "Igor Tudor", "Igor Vrablic", "Ihor Belanov",
  "Ike Shorunmu", "Ildo Maneiro", "İlhan Mansız", "Ilia Tsymbalar",
  "Ilian Iliev", "Ilian Kiriakov", "Ilie Dumitrescu", "Ilija Petković",
  "Iliya Dyakov", "Iliya Valov", "Illiasu Shilla", "Imed Ben Younes",
  "Imed Mhedhebi", "Imre Garaba", "Imre Kiss", "Inge Ejderstedt",
  "Ingemar Erlandsson", "Ioan Andone", "Ioan Lupescu", "Ioan Sabău",
  "Ioannis Kalitzakis", "Ion Andoni Goikoetxea", "Ion Dumitru", "Ion Vlădoiu",
  "Iosif Rotariu", "Iraj Danaeifard", "Ireneusz Jeleń", "Isaác Brizuela",
  "Isaac Okoronkwo", "Isaac Terrazas", "Isaac Vorsah", "Isidoro Díaz",
  "Isidoro San José", "Islam Slimani", "Ismaël Diomandé", "Ismael Fuentes",
  "Ismail Mohammed Sharif", "Ismail Youssef", "Israel Castro", "Issah Ahmed",
  "István Halász", "István Kocsis", "Itumeleng Khune", "Itzhak Shum",
  "Iulian Chiriţă", "Iulian Filipescu", "Ivan Bošnjak", "Ivan Buljan",
  "Iván Campo", "Iván Córdoba", "Ivan Davidov", "Ivan Dimitrov",
  "Ivan Ergić", "Ivan Franjić", "Ivan Gudelj", "Ivan Hašek",
  "Iván Helguera", "Ivan Hrdlička", "Iván Hurtado", "Iván Kaviedes",
  "Ivan Klasnić", "Ivan Leko", "Ivan Močinić", "Ivan Nielsen",
  "Ivan Obradović", "Ivan Perišić", "Ivan Pudar", "Ivan Rakitić",
  "Ivan Stoyanov", "Iván Valenciano", "Ivan Vicelich", "Ivan Yaremchuk",
  "Ivan Zafirov", "Iván Zamorano", "Ivano Bordon", "Ivaylo Andonov",
  "Ivaylo Petkov", "Ivaylo Yordanov", "Ive Jerolimov", "Ivica Dragutinović",
  "Ivica Kralj", "Ivica Olić", "Ivica Šurjak", "Ivica Vastić",
  "Ivo Knoflíček", "Ivo Rudic", "Ivo Viktor", "Izet Hajrović",
  "Jaap Stam", "Jabu Pule", "Jacek Bąk", "Jacek Kazimierski",
  "Jacek Krzynówek", "Jacek Zieliński", "Jack Charlton", "Jack Reilly",
  "Jack Wilshere", "Jackie McNamara", "Jackson Martínez", "Jacky Munaron",
  "Jacky Peeters", "Jacob Laursen", "Jacob Lekgetho", "Jacques Beurlet",
  "Jacques Duquesne", "Jacques N'Guea", "Jacques Songo'o", "Jaime Ayoví",
  "Jaime Duarte", "Jaime Magalhães", "Jaime Moreno", "Jaime Ordiales",
  "Jaime Pacheco", "Jaime Portillo", "Jaime Rodríguez", "Jaime Villegas",
  "Jairzinho", "Jakob Poulsen", "Jalal Hosseini", "Jalili Fadili",
  "Jamal Al-Qabendi", "Jamal Ali Hamza", "Jamal Sellami", "Jamba",
  "James Bannatyne", "James Holland", "James Milner", "James Obiorah",
  "James Rodríguez", "James Troisi", "Jamie Lowery", "Jan Åge Fjørtoft",
  "Jan Bartram", "Jan Berger", "Ján Čapkovič", "Jan Ceulemans",
  "Jan Domarski", "Ján Ďurica", "Jan Eriksson", "Jan Fiala",
  "Jan Furtok", "Jan Heintze", "Jan Jałocha", "Jan Jongbloed",
  "Jan Karaś", "Ján Kocian", "Jan Koller", "Ján Kozák",
  "Jan Kromkamp", "Jan Mølby", "Jan Michaelsen", "Jan Möller",
  "Ján Mucha", "Jan Olsson", "Ján Pivarník", "Jan Polák",
  "Jan Poortvliet", "Jan Stejskal", "Jan Tomaszewski", "Jan Urban",
  "Jan Vennegoor of Hesselink", "Jan Verheyen", "Jan Vertonghen", "Jan Wouters",
  "Ján Zlocha", "Jang Dae-Il", "Jang Hyung-Seok", "Janusz Kupcewicz",
  "Jared Borgetti", "Jaromír Blažek", "Jaroslav Plašil", "Jaroslav Pollák",
  "Jasem Bahman", "Jasem Yaqoub", "Jasmin Fejzić", "Jasmin Handanovič",
  "Jason Čulina", "Jason Davidson", "Jason McAteer", "Jason Scotland",
  "Jasper Cillessen", "Javad Allahverdi", "Javad Kazemian", "Javad Nekounam",
  "Javad Zarincheh", "Javi Martínez", "Javier Aguirre", "Javier Aquino",
  "Javier Cárdenas", "Javier de Pedro", "Javier Fragoso", "Javier González",
  "Javier Guzmán", "Javier Hernández", "Javier Margas", "Javier Pastore",
  "Javier Saviola", "Javier Valdivia", "Javier Zeoli", "Jawhar Mnari",
  "Jay DeMerit", "Jean-Alain Boumsong", "Jean Beausejour", "Jean Castaneda",
  "Jean-Claude Désir", "Jean-Claude Pagal", "Jean-Daniel Akpa-Akpro", "Jean Dockx",
  "Jean-François De Sart", "Jean-François Larios", "Jean-Herbert Austin", "Jean-Jacques Gosso",
  "Jean-Jacques Tizié", "Jean Kalala N'Tumba", "Jean-Luc Ettori", "Jean Makoun",
  "Jean-Marc Ferreri", "Jean-Marc Guillou", "Jean-Marie Pfaff", "Jean-Marie Trappeniers",
  "Jean-Paul Abalo", "Jean-Paul Bertrand-Demanes", "Jean Petit", "Jean-Pierre Fiala",
  "Jean-Pierre Papin", "Jean-Pierre Tokoto", "Jean Thissen", "Jean Tigana",
  "Jeff Agoos", "Jeff Astle", "Jefferson", "Jefferson Montero",
  "Jens Jørn Bertelsen", "Jens Jeremies", "Jens Lehmann", "Jens Nowotny",
  "Jeong Gi-Dong", "Jeremain Lens", "Jeremy Brockie", "Jeremy Christie",
  "Jérémy Toulalan", "Jerko Leko", "Jermain Defoe", "Jermaine Jenas",
  "Jermaine Jones", "Jerry Bengtson", "Jerry Palacios", "Jerry Sikhosana",
  "Jervis Drummond", "Jerzy Dudek", "Jerzy Gorgoń", "Jes Høgh",
  "Jesper Blomqvist", "Jesper Christiansen", "Jesper Grønkjær", "Jesper Olsen",
  "Jesús Arellano", "Jesus Goyzueta", "Jesús María Satrústegui", "Jesús María Zamora",
  "Jesús Martínez", "Jesús Navas", "Ji Dong-Won", "Ji Yun-Nam",
  "Jiang Jin", "Jim Bett", "Jim Blyth", "Jim Cleary",
  "Jim Holton", "Jim Leighton", "Jim Milisavljevic", "Jim Platt",
  "Jim Stewart", "Jimmy Banks", "Jimmy Conrad", "Jimmy Floyd Hasselbaink",
  "Jimmy Johnstone", "Jimmy Mackay", "Jimmy Nicholl", "Jimmy Quinn",
  "Jimmy Rooney", "Jimmy Steward", "Jiří Němec", "Jiří Štajner",
  "Jô", "Joachim Björklund", "Joachim Fritsche", "Joachim Streich",
  "Joakim Nilsson", "Joan Capdevila", "João Moutinho", "João Pereira",
  "João Pinto", "João Ricardo", "Joao Rojas", "Joaquín",
  "Joaquín del Olmo", "Joaquín Ventura", "Joe Bizera", "Joe Corrigan",
  "Joe Harper", "Joe Jordan", "Joe-Max Moore", "Joel",
  "Joël Bats", "Joel Campbell", "Joël Epalle", "Joël Matip",
  "Joel Sánchez", "Joël Veltman", "Joey Didulica", "Johan Boskamp",
  "Johan Cruyff", "Johan Devrindt", "Johan Djourou", "Johan Elmander",
  "Johan Micoud", "Johan Mjällby", "Johan Neeskens", "Johan Rodríguez",
  "Johan Walem", "Johann Dihanich", "Johann Pregesbauer", "Johann Vogel",
  "John Aldridge", "John Aloisi", "John Alvbåge", "John Blackley",
  "John Bosman", "John Boye", "John Brooks", "John Byrne",
  "John Collins", "John de Wolf", "John Doyle", "John Eriksen",
  "John Harkes", "John Harold Lozano", "John Heitinga", "John Hill",
  "John McClelland", "John Mensah", "John Moshoeu", "John O'Brien",
  "John O'Neill", "John Obi Mikel", "John Paintsil", "John Robertson",
  "John Sheridan", "John Sivebæk", "John Stollmeyer", "John Utaka",
  "John van 't Schip", "John van Loen", "John Wark", "John Wilmar Pérez",
  "Johnny Acosta", "Johnny Ekström", "Johnny Herrera", "Johnny Jameson",
  "Johnny Leoni", "Johnny Palacios", "Johnny Rep", "Johnny Warren",
  "Johnny Watkiss", "Jon Dahl Tomasson", "Jonás Gutiérrez", "Jonas Thern",
  "Jonathan Bornstein", "Jonathan de Guzmán", "Jonathan Gould", "Jonathan Mensah",
  "Jonathan Santana", "Jonathan Spector", "Jong Tae-Se", "Jonny Magallón",
  "Joop Hiele", "Jordan Ayew", "Jordy Clasie", "Jörg Böhme",
  "Jörg Heinrich", "Jorge Amado Nunes", "Jorge Andrade", "Jorge Barrios",
  "Jorge Battaglia", "Jorge Bermúdez", "Jorge Bolaño", "Jorge Borelli",
  "Jorge Burruchaga", "Jorge Campos", "Jorge Carrascosa", "Jorge Claros",
  "Jorge Costa", "Jorge da Silva", "Jorge Fucile", "Jorge Guagua",
  "Jorge Guasch", "Jorge Luis Campos", "Jorge Martins", "Jorge Mendonça",
  "Jorge Núñez", "Jorge Olaechea", "Jorge Olguín", "Jorge Otero",
  "Jorge Rodríguez", "Jorge Socías", "Jorge Torres Nilo", "Jorge Valdano",
  "Jorge Valdivia", "Jorge Vásquez", "Jörgen Augustsson", "Jorginho",
  "Joris Mathijsen", "Jos Daerden", "José António", "José Antonio Camacho",
  "José Antonio Castro", "José Antonio Reyes", "José Basualdo", "José Batista",
  "José Cardozo", "José Carlos Chaves", "José Chamot", "José Clayton",
  "José Cruz", "José Daniel Valencia", "José de Jesús Corona", "José del Castillo",
  "José Fernández", "José Francisco Cevallos", "José Francisco Jovel", "José Francisco Torres",
  "José Gómez", "José González", "José Holebas", "José Jaikel",
  "José Juan Vázquez", "José Luis Brown", "José Luis Caminero", "José Luis Chilavert",
  "José Luis Cuciuffo", "José Luis González", "José Luis Munguía", "José Luis Perlaza",
  "José Luis Rugamas", "José Luis Salgado", "José Luis Sierra", "José Manuel Ochotorena",
  "José Mari Bakero", "José María Basanta", "José María Giménez", "José María Pazo",
  "José María Rivas", "José Miguel Cubero", "José Milton Melgar", "José Molina",
  "José Montiel", "José Navarro", "José Oscar Herrera", "José Pedro Fuenzalida",
  "José Perdomo", "José Pilar Reyes", "José Pintos Saldanha", "José Porras",
  "José Quintanilla", "José Ramón Alexanko", "José Ribeiro", "José Ricardo Pérez",
  "José Rojas", "José Santa", "José Serrizuela", "José Van Tuyne",
  "José Vantolrá", "José Velásquez", "José Vicente Sánchez", "José Zalazar",
  "Joseba Etxeberria", "Josef Degeorgi", "Josef Hickersberger", "Josef Jurkanin",
  "Josep Guardiola", "Joseph-Antoine Bell", "Joseph-Désiré Job", "Joseph Elanga",
  "Joseph Enanga", "Joseph Kamga", "Joseph-Marion Leandré", "Joseph N'Do",
  "Joseph Yobo", "Josh Wolff", "Joshua Kennedy", "Josimar",
  "Josip Drmić", "Josip Katalinski", "Josip Šimunić", "Josip Skoko",
  "Josip Weber", "Jostein Flo", "Josué", "Jovan Aćimović",
  "Jozef Adamec", "Jozef Barmoš", "Jozef Chovanec", "Jozef Kukučka",
  "Józef Młynarczyk", "Józef Wandzik", "József Andrusch", "József Csuhay",
  "József Kardos", "József Kiprich", "József Nagy", "József Szendrei",
  "József Tóth", "József Varga", "Jozy Altidore", "Juan",
  "Juan Antonio Pizzi", "Juan Antonio Señor", "Juan Barbas", "Juan Cáceres",
  "Juan Camilo Zúñiga", "Juan Carlos Ablanedo", "Juan Carlos Burbano", "Juan Carlos Chávez",
  "Juan Carlos Franco", "Juan Carlos García", "Juan Carlos Letelier", "Juan Carlos Masnik",
  "Juan Carlos Oblitas", "Juan Carlos Paredes", "Juan Carlos Valerón", "Juan Castillo",
  "Juan Cayasso", "Juan Cruz", "Juan de Dios Ramírez Perales", "Juan Fernando Quintero",
  "Juan Guillermo Cuadrado", "Juan Ignacio Basaguren", "Juan José Rodríguez", "Juan Machuca",
  "Juan Manuel Alejandrez", "Juan Manuel Asensi", "Juan Manuel Peña", "Juan Mata",
  "Juan Mujica", "Juan Muñante", "Juan Olivares", "Juan Pablo Montes",
  "Juan Pablo Sorín", "Juan Ramón Martínez", "Juan Rodríguez", "Juan Román Riquelme",
  "Juan Sebastián Verón", "Juan Silva", "Juan Simón", "Juan Torales",
  "Juanele", "Juanfran", "Juanito", "Juergen Sommer",
  "Julen Guerrero", "Julen Lopetegui", "Jules Onana", "Julián Coronel",
  "Julian Draxler", "Julian Green", "Juliano Belletti", "Julio Alberto",
  "Júlio Baptista", "Julio Baylón", "Julio Cardeñosa", "Júlio César",
  "Julio César Arzú", "Julio César Baldivieso", "Julio César Cáceres", "Julio César Cortés",
  "Julio César Enciso", "Julio César Jiménez", "Julio César Manzur", "Julio César Romero",
  "Julio César Uribe", "Julio César Yegros", "Julio Cruz", "Julio dos Santos",
  "Julio Losada", "Julio Montero Castillo", "Julio Morales", "Julio Olarticoechea",
  "Julio Salinas", "Julius Aghahowa", "Július Bielik", "Jung Sung-Ryong",
  "Junichi Inamoto", "Juninho", "Júnior", "Júnior Baiano",
  "Júnior Díaz", "Jupp Heynckes", "Jupp Kapellmann", "Juraj Kucka",
  "Jürg Studer", "Jürgen Croy", "Jürgen Grabowski", "Jürgen Klinsmann",
  "Jürgen Kohler", "Jürgen Pommerenke", "Jürgen Sparwasser", "Jurica Jerković",
  "Jurica Vranješ", "Justice Christopher", "Justo Villar", "Juwon Oshaniwa",
  "Kabasu Babo", "Kacem Slimani", "Kader Keïta", "Kafula Ngoie",
  "Kagisho Dikgacoi", "Kaies Ghodhbane", "Kakhi Asatiani", "Kakoko Etepé",
  "Kalambay Otepa", "Kali", "Kalidou Cissokho", "Kálmán Kovács",
  "Kalu Uche", "Kamel Chebli", "Kamil Kopúnek", "Kamil Kosowski",
  "Kang Deuk-Soo", "Kang Min-Soo", "Kanga Akalé", "Karel Poborský",
  "Karel Stromšík", "Karim Ansarifard", "Karim Bagheri", "Karim Essediri",
  "Karim Haggui", "Karim Maroc", "Karim Matmour", "Karim Mohammed Allawi",
  "Karim Saddam Minshid", "Karim Saidi", "Karim Ziani", "Karl Allgöwer",
  "Karl-Heinz Riedle", "Karl-Heinz Rummenigge", "Karl-Heinz Schnellinger", "Karl Petter Løken",
  "Karl Svensson", "Karlheinz Förster", "Karol Dobiaš", "Karol Jokl",
  "Károly Csapó", "Kasey Keller", "Kasper Bøgelund", "Katlego Mphela",
  "Kazadi Mwamba", "Kazimierz Deyna", "Kazimierz Kmiecik", "Kazimierz Przybyś",
  "Kazuyuki Toda", "Kees van Ierssel", "Keiji Tamada", "Keisuke Tsuboi",
  "Keith MacKay", "Keith Newton", "Kelvin Jack", "Kembo Uba Kembo",
  "Kengo Nakamura", "Kennet Andersson", "Kenneth Omeruo", "Kenny Burns",
  "Kenny Cresswell", "Kenny Cunningham", "Kenny Sansom", "Kent Karlsson",
  "Kent Nielsen", "Kenwyne Jones", "Kerry Dixon", "Kevin Gallacher",
  "Kevin Großkreutz", "Kevin Keegan", "Kevin Kilbane", "Kevin Mirallas",
  "Kevin Moran", "Kevin-Prince Boateng", "Kevin Sheedy", "Kew Jaliens",
  "Keylor Navas", "Khaled Aziz", "Khaled Badra", "Khaled Gasmi",
  "Khalid Al-Muwallid", "Khalid Boulahrouz", "Khalid Ismaïl", "Khalil Azmi",
  "Khalil Ghanim", "Khalil Mohammed Allawi", "Khalilou Fadiga", "Khamis Al-Owairan",
  "Khemais Labidi", "Khodadad Azizi", "Khoren Oganesian", "Khosro Heydari",
  "Ki Sung-Yong", "Ki Sung-Yueng", "Kibonge Mafu", "Kidumu Mantantu",
  "Kiko", "Kilasu Massamba", "Kily González", "Kim Bo-Kyung",
  "Kim Byung-Ji", "Kim Chang-Soo", "Kim Do-Heon", "Kim Do-Hoon",
  "Kim Do-Keun", "Kim Dong-Jin", "Kim Hyung-Il", "Kim Jae-Sung",
  "Kim Jin-Kyu", "Kim Jong-Boo", "Kim Joo-Sung", "Kim Jung-Woo",
  "Kim Källström", "Kim Kum-Il", "Kim Kyong-Il", "Kim Myong-Gil",
  "Kim Myong-Won", "Kim Nam-Il", "Kim Pan-Keun", "Kim Poong-Joo",
  "Kim Pyung-Seok", "Kim Sam-Soo", "Kim Sang-Sik", "Kim Seung-Gyu",
  "Kim Shin-Wook", "Kim Tae-Young", "Kim Yong-Dae", "Kim Yong-Jun",
  "Kim Yong-Se", "Kim Young-Chul", "Kim Young-Gwon", "Kim Young-Kwang",
  "Kiriakos Karataidis", "Kiril Dojčinovski", "Kiril Ivkov", "Kiril Milanov",
  "Kisho Yano", "Kjetil Rekdal", "Klaas-Jan Huntelaar", "Klas Ingesson",
  "Klaus Allofs", "Klaus Augenthaler", "Klaus Berggreen", "Klaus-Dieter Sieloff",
  "Klaus Fichtel", "Klaus Fischer", "Klaus Lindenberger", "Kléberson",
  "Ko Jeong-Woon", "Ko Jong-Soo", "Kodjovi Obilale", "Kōji Nakata",
  "Koke", "Kolo Touré", "Konrad Weise", "Koo Ja-Cheol",
  "Kornel Saláta", "Kossi Agassa", "Kostadin Kostadinov", "Kostas Chalkias",
  "Kostas Katsouranis", "Kostas Manolas", "Kostas Mitroglou", "Krasimir Borisov",
  "Krassimir Balakov", "Krister Kristensson", "Krunoslav Jurčić", "Krzysztof Pawlak",
  "Kuami Agboh", "Kunle Odunlami", "Kurt Axelsson", "Kurt Bernard",
  "Kurt Jara", "Kurt Russ", "Kurt Welzl", "Kwadwo Asamoah",
  "Kwak Tae-Hwi", "Kyle Beckerman", "Labid Khalifa", "Ladislao Mazurkiewicz",
  "Ladislav Jurkemik", "Ladislav Kuna", "Ladislav Petráš", "Ladislav Vízek",
  "Lahcen Abrami", "Lahcen Ouadani", "Lajos Détári", "Lajos Sătmăreanu",
  "Lakhdar Belloumi", "Lamá", "Lamine Ben Aziza", "Lamine Diatta",
  "Lance Davids", "Landon Donovan", "Landry N'Guémo", "Larbi El Hadi",
  "Lars Bohinen", "Lars Eriksson", "Lars Høgh", "Lars Jacobsen",
  "Lars Ricken", "László Bálint", "László Dajka", "László Disztl",
  "László Fazekas", "László Kiss", "László Kovács", "László Nagy",
  "László Pusztai", "Lauren Etame Mayer", "Laurent Blanc", "Laurent Ciman",
  "Laurent Koscielny", "Lázár Szentes", "Lazaros Christodoulopoulos", "Leandro",
  "Leandro Cufré", "Leão", "Lebo Lebo", "Lebohang Morula",
  "Ledley King", "Lee Addy", "Lee Bum-Young", "Lee Carsley",
  "Lee Chun-Soo", "Lee Chung-Yong", "Lee Dong-Gook", "Lee Eul-Yong",
  "Lee Heung-Sil", "Lee Ho", "Lee Jong-Hwa", "Lee Jung-Soo",
  "Lee Keun-Ho", "Lee Lim-Saeng", "Lee Min-Sung", "Lee Sang-Hun",
  "Lee Sang-Yoon", "Lee Seung-Yeoul", "Lee Tae-Ho", "Lee Woon-Jae",
  "Lee Yong", "Lee Young-jin", "Lee Young-Pyo", "Lei Clijsters",
  "Léider Preciado", "Leif Engqvist", "Leif Eriksson", "Leif Målberg",
  "Leighton Baines", "Leivinha", "Lennart Larsson", "Leo Bertos",
  "Leo Franco", "Leo Van Der Elst", "Léon Jeck", "Léon Semmeling",
  "León Villa", "Leonardo", "Leonardo Astrada", "Leonardo Cuéllar",
  "Leonardo González", "Leonardo Rodríguez", "Leonardo Véliz", "Leonel Álvarez",
  "Leonid Buryak", "Leonid Shmuts", "Leopoldo Luque", "Leopoldo Vallejos",
  "Leroy Fer", "Lesław Ćmikiewicz", "Lester Morgan", "Lev Yashin",
  "Li Tie", "Li Weifeng", "Li Xiaopeng", "Liassine Cadamuro-Bentaïba",
  "Libor Radimec", "Libor Sionko", "Lido Vieri", "Liédson",
  "Linval Dixon", "Lionel Charbonnier", "Lionel Scaloni", "Lionello Manfredonia",
  "Liviu Ciobotariu", "Lizardo Garrido", "Ljubinko Drulović", "Lobilo Boba",
  "Locó", "Loïc Feudjou", "Loïc Rémy", "Lorenzo Minotti",
  "Lorenzo Staelens", "Lothar Kurbjuweit", "Lothar Matthäus", "Lou Macari",
  "Louis-Paul M'Fédé", "Louis Saha", "Loukas Vyntra", "Lounès Gaouaoui",
  "Love", "Ľubomír Moravčík", "Luboš Kubík", "Luc Millecamps",
  "Luc Nilis", "Luca Bucci", "Luca Marchegiani", "Luca Toni",
  "Lucas Barrios", "Lucas Biglia", "Lucas Digne", "Lucas Neill",
  "Lucas Radebe", "Lucas Thwala", "Lucho González", "Lucian Marinescu",
  "Luciano Castellini", "Luciano Re Cecconi", "Luciano Spinosi", "Lucien Mettomo",
  "Lúcio", "Luděk Mikloško", "Ludo Coeck", "Ludovic Assemoassa",
  "Ludovic Magnin", "Luigi Apolloni", "Luigi De Agostini", "Luigi Di Biagio",
  "Luigi Riva", "Luis Antonio Moreno", "Luis Antonio Valdéz", "Luis Arconada",
  "Luís Boa Morte", "Luis Caballero", "Luis Carlos Perea", "Luis Cristaldo",
  "Luis Cruzado", "Luis Cubilla", "Luis Enrique", "Luis Ernesto Michel",
  "Luis Ernesto Pérez", "Luís Fabiano", "Luis Fajardo", "Luis Fernández",
  "Luis Fernando Herrera", "Luis Flores", "Luis Gabelo Conejo", "Luis Galván",
  "Luis García", "Luis Garisto", "Luis Garrido", "Luis Gómez",
  "Luis Guevara Mora", "Luis Hernández", "Luis Islas", "Luis López",
  "Luis Marín", "Luis Miguel Salvador", "Luis Musrri", "Luís Neto",
  "Luis Oliveira", "Luís Pereira", "Luis Ramallo", "Luis Ramírez",
  "Luis Reyna", "Luis Roberto Alves", "Luis Rubiños", "Luis Saritama",
  "Luís Sobrinho", "Luis Ubiñas", "Luisão", "Luiz Gustavo",
  "Luizão", "Luizinho", "Luka Peruzović", "Luke Wilkshire",
  "Lukman Haruna", "Lyuboslav Penev", "Ma Mingyu", "Maad Ibrahim Majid",
  "Maarten Stekelenburg", "Mabrouk Zaid", "MacBeth Sibaya", "MacDonald Mukansi",
  "Maciej Murawski", "Maciej Żurawski", "Madjid Bougherra", "Magdi Abdelghani",
  "Magdy Tolba", "Mágico González", "Magnus Andersson", "Magnus Erlingmark",
  "Magnus Hedman", "Magnus Kihlstedt", "Magnus Svensson", "Mahboub Juma'a",
  "Mahmoud Guendouz", "Maicon", "Majed Abdullah", "Majeed Waris",
  "Majid Bishkar", "Makhtar N'Diaye", "Makoto Hasebe", "Maksim Kanunnikov",
  "Maksym Kalynychenko", "Mal Donaghy", "Malek Mouath", "Mamadou Sakho",
  "Mamam Cherif Touré", "Mana Mamuwene", "Manabu Saitō", "Manfred Kaltz",
  "Manfred Linzmaier", "Manfred Manglitz", "Manfred Schäfer", "Manfred Zsak",
  "Maniche", "Manolo", "Mansour Al-Thagafi", "Mantorras",
  "Manuel Amoros", "Manuel Bento", "Manuel Jiménez", "Manuel Nájera",
  "Manuel Negrete", "Manuel Neira", "Manuel Rojas", "Manuel Sanchís",
  "Manuel Vidrio", "Maouhoub Ghazouani", "Marañón", "Marat Izmailov",
  "Marc Baecke", "Marc Berdoll", "Marc Degryse", "Marc Emmers",
  "Marc Hottiger", "Marc Millecamps", "Marc Planus", "Marc Rieper",
  "Marc Van Der Linden", "Marc-Vivien Foé", "Marc Wilmots", "Marcel Mahouvé",
  "Marcelino", "Marcelino Bernal", "Marcell Jansen", "Marcelo",
  "Marcelo Balboa", "Marcelo Brozović", "Marcelo Delgado", "Marcelo Díaz",
  "Marcelo Gallardo", "Marcelo Ramírez", "Marcelo Romero", "Marcelo Salas",
  "Marcelo Torrico", "Marcelo Trobbiani", "Marcelo Vega", "Marcin Baszczyński",
  "Marcin Żewłakow", "Márcio Santos", "Marco Abreu", "Marco Airosa",
  "Marco Amelia", "Marco Antônio", "Marco Bode", "Marco Caneira",
  "Marco Cornez", "Marco Delvecchio", "Marco Estrada", "Marco Etcheverry",
  "Marco Fabián", "Marco Grassi", "Marco Materazzi", "Marco Padalino",
  "Marco Parolo", "Marco Pascolo", "Marco Sandy", "Marco Streller",
  "Marco Tardelli", "Marco Ureña", "Marco van Basten", "Marco Wölfli",
  "Marco Zoro", "Marcos", "Marcos Rivas", "Marcos Rojo",
  "Marcos Senna", "Marcus Allbäck", "Marcus Gayle", "Marcus Hahnemann",
  "Marcus Tulio Tanaka", "Marek Čech", "Marek Dziuba", "Marek Hamšík",
  "Marek Heinz", "Marek Jankulovski", "Marek Koźmiński", "Marek Kusto",
  "Marek Ostrowski", "Marek Sapara", "Marian Hristov", "Marian Ivan",
  "Marián Masný", "Mariano Andújar", "Mariano Pernía", "Marijan Mrmić",
  "Marin Tufan", "Marinho Chagas", "Marinho Peres", "Marinko Galič",
  "Mário", "Mario Balotelli", "Mario Basler", "Mario Bertini",
  "Mario Bolatti", "Mario Castillo", "Mario Eggimann", "Mario Galindo",
  "Mario Gavranović", "Mario Gómez", "Mario González", "Mario Götze",
  "Mario Haas", "Mario Kempes", "Mario Mandžukić", "Mario Martínez",
  "Mario Medina", "Mario Méndez", "Mario Monge", "Mario Osbén",
  "Mario Pérez", "Mario Pinedo", "Mario Regueiro", "Mario Saralegui",
  "Mario Soto", "Mario Stanić", "Mario Tokić", "Mario Trejo",
  "Mario Velarde", "Mario Yepes", "Marius Lăcătuş", "Marius Trésor",
  "Mariusz Jop", "Mariusz Lewandowski", "Mark Bresciano", "Mark Caughey",
  "Mark Fish", "Mark González", "Mark Hateley", "Mark Iuliano",
  "Mark Kinsella", "Mark Milligan", "Mark Paston", "Mark Schwarzer",
  "Mark van Bommel", "Mark Viduka", "Mark Wright", "Marko Babić",
  "Marko Marin", "Marko Pantelić", "Marko Rehmer", "Marko Simeunovič",
  "Marko Šuler", "Markus Babbel", "Markus Rosenberg", "Markus Schopp",
  "Marlon Ayoví", "Marouane Fellaini", "Martin Amerhauser", "Martin Brunner",
  "Martin Buchan", "Martín Cáceres", "Martin Dahlin", "Martín Demichelis",
  "Martin Hiden", "Martin Hoffmann", "Martin Jørgensen", "Martin Jakubko",
  "Martin Jiránek", "Martin Laursen", "Martin O'Neill", "Martín Palermo",
  "Martin Peters", "Martin Petráš", "Martin Rueda", "Martín Silva",
  "Martin Škrtel", "Martin Wagner", "Márton Esterházy", "Marvin Andrews",
  "Marvin Chávez", "Marvin Obando", "Masahiko Inoha", "Masami Ihara",
  "Masashi Nakayama", "Masashi Oguro", "Masato Morishige", "Masayuki Okano",
  "Masoud Shojaei", "Massamasso Tchangai", "Massimo Luongo", "Massimo Oddo",
  "Matej Mavrič", "Mateja Kežman", "Mateo Kovačić", "Mateus",
  "Mathew Leckie", "Mathew Ryan", "Mathieu Debuchy", "Mathieu Valbuena",
  "Mathis Bolly", "Matías Almeyda", "Matías Fernández", "Mats Gren",
  "Mats Magnusson", "Matt Besler", "Matt Elliott", "Matt Holland",
  "Matt McKay", "Matteo Darmian", "Matthew Amoah", "Matthew Booth",
  "Matthew Špiranović", "Matthew Upson", "Matthias Ginter", "Matthias Herget",
  "Matthias Sammer", "Mattia De Sciglio", "Mattia Perin", "Mattias Jonson",
  "Maurice Edu", "Maurice Malpas", "Maurice Martens", "Mauricio Alfaro",
  "Mauricio Aros", "Mauricio Isla", "Mauricio Manzano", "Mauricio Montero",
  "Mauricio Pineda", "Mauricio Pinilla", "Mauricio Pochettino", "Mauricio Ramos",
  "Mauricio Rodríguez", "Mauricio Sabillón", "Mauricio Serna", "Mauricio Solís",
  "Mauricio Victorino", "Mauricio Wright", "Maurits De Schrijver", "Maurizio Gaudino",
  "Mauro Bellugi", "Mauro Camoranesi", "Mauro Galvão", "Mauro Lustrinelli",
  "Mauro Silva", "Mauro Tassotti", "Mavuba Mafuila", "Max Gradel",
  "Max Hagmayr", "Max Lorenz", "Max Tolson", "Maxi Pereira",
  "Maxi Rodríguez", "Maxim Choupo-Moting", "Maxime Bossis", "Máximo Banguera",
  "Maxwell", "Maya Yoshida", "Mayanga Maku", "Maynor Figueroa",
  "Mazinho", "Mbo Mpenza", "Mbungu Ekofa", "Medhi Lacen",
  "Mehdi Ben Slimane", "Mehdi Cerbah", "Mehdi Mahdavikia", "Mehdi Mostefa",
  "Mehdi Nafti", "Mehdi Pashazadeh", "Mehrdad Minavand", "Mehrdad Pouladi",
  "Mehrzad Madanchi", "Melvin Brown", "Menachem Bello", "Mendonça",
  "Mensur Mujdža", "Michał Żewłakow", "Michael Arroyo", "Michael Babatunde",
  "Michael Barrantes", "Michael Baur", "Michael Beauchamp", "Michael Bradley",
  "Michael Carrick", "Michael Dawson", "Michael Emenalo", "Michael Klein",
  "Michael Konsel", "Michael Lang", "Michael Laudrup", "Michael McGlinchey",
  "Michael Reiziger", "Michael Rodríguez", "Michael Schjønberg", "Michael Streiter",
  "Michael Svensson", "Michael Tarnat", "Michael Uchebo", "Michael Umaña",
  "Michal Bílek", "Michalis Sifakis", "Míchel", "Michel Bastos",
  "Michel Bibard", "Michel de Wolf", "Michel Kaham", "Michel Pensée",
  "Michel Platini", "Michel Preud'homme", "Michel Renquin", "Míchel Salgado",
  "Michel Vorm", "Mick McCarthy", "Mick Mills", "Mickaël Landreau",
  "Miguel", "Miguel Ángel", "Miguel Ángel Alonso", "Miguel Ángel Benítez",
  "Miguel Ángel Brindisi", "Miguel Ángel Díaz", "Miguel Ángel Gamboa", "Miguel Ángel Nadal",
  "Miguel Ángel Neira", "Miguel Ángel Ponce", "Miguel Ángel Santoro", "Miguel Bossio",
  "Miguel Calero", "Miguel Davis", "Miguel España", "Miguel Guerrero",
  "Miguel Gutiérrez", "Miguel Layún", "Miguel Oviedo", "Miguel Pardeza",
  "Miguel Pinto", "Miguel Ramírez", "Miguel Rimba", "Miguel Segura",
  "Miguel Tendillo", "Miguel Veloso", "Migueli", "Mihai Ivăncescu",
  "Mihai Mocanu", "Miiko Albornoz", "Mikael Nilsson", "Mikaël Silvestre",
  "Mike Burns", "Mike Hanke", "Mike Lapper", "Mike Sorber",
  "Mike Sweeney", "Mike Verstraeten", "Mike Windischmann", "Mikkel Beckmann",
  "Mikkel Diskerud", "Miklos Molnar", "Milan Albrecht", "Milan Baroš",
  "Milan Dudić", "Milan Jovanović", "Milan Luhový", "Milan Osterc",
  "Milan Rapaić", "Mile Jedinak", "Mile Sterjovski", "Milen Petkov",
  "Milenko Ačimovič", "Milivoje Novakovič", "Milko Gaydarski", "Miloš Hrstić",
  "Miloš Krasić", "Miloš Ninković", "Miloš Šestić", "Miloy",
  "Minas Hantzidis", "Mineiro", "Mini Jakobsen", "Miodrag Belodedici",
  "Miralem Pjanić", "Miran Pavlin", "Mirandinha", "Mircea Lucescu",
  "Mircea Rednic", "Mirosław Bulzacki", "Mirosław Justek", "Mirosław Szymkowiak",
  "Miroslav Đukić", "Miroslav Kadlec", "Miroslav Pavlović", "Miroslav Stević",
  "Miroslav Stoch", "Mirsad Baljić", "Mišo Brečko", "Missael Espinoza",
  "Mitchell Langerak", "Mitsuo Ogasawara", "Mladen Dabanovič", "Mladen Krstajić",
  "Mladen Rudonja", "Mladen Vasilev", "Mo Johnston", "Mobi Oparaku",
  "Modesto Soruco", "Moeneeb Josephs", "Mogens Krogh", "Mohamed Akid",
  "Mohamed Al-Deayea", "Mohamed Al-Jawad", "Mohamed Ben Mouza", "Mohamed Ben Rehaiem",
  "Mohamed Kader", "Mohamed Mkacher", "Mohamed Salim", "Mohamed Zemmamouche",
  "Mohammad Al-Bishi", "Mohammad Al-Shalhoub", "Mohammad Khakpour", "Mohammad Khouja",
  "Mohammad Massad", "Mohammad Nosrati", "Mohammad Sadeghi", "Mohammadou Idrissou",
  "Mohammed Al-Jahani", "Mohammed Al-Khilaiwi", "Mohammed Al-Khojali", "Mohammed Ameen",
  "Mohammed Chaib", "Mohammed Chaouch", "Mohammed El Filali", "Mohammed Hazzaz",
  "Mohammed Kaci Said", "Mohammed Karam", "Mohammed Mahroufi", "Mohammed Noor",
  "Mohammed Rabiu", "Mohammed Sahil", "Mohammed Samadi", "Mohammed Timoumi",
  "Moharram Navidkia", "Mohsen Labidi", "Mohsin Al-Harthi", "Moisés Villarroel",
  "Mokhtar Dhouib", "Mokhtar Hasni", "Mokhtar Naili", "Mordechai Spiegler",
  "Moreno Torricelli", "Morgan De Sanctis", "Morgan Schneiderlin", "Morten Olsen",
  "Morten Wieghorst", "Moshe Romano", "Motohiro Yamaguchi", "Moulay Khanousi",
  "Mouncif El Haddaoui", "Mounir Boukadida", "Mourad Amara", "Mourad Melki",
  "Mousa Dembélé", "Moussa N'Diaye", "Moussa Sissoko", "Moustapha Choukri",
  "Moustapha Salifou", "Muamer Vugdalič", "Muayad Al-Haddad", "Mubarak Ghanim",
  "Mubarak Marzouq", "Muhamed Bešić", "Muhsin Musabah", "Müller",
  "Mun In-Guk", "Murdo MacLeod", "Murtaz Khurtsilava", "Mustafa El Biyaz",
  "Mustafa El Haddaoui", "Mustafa İzzet", "Mustafa Kouici", "Mustafa Merry",
  "Mustapha Chadili", "Mustapha Dahleb", "Mustapha Hadji", "Mutiu Adepoju",
  "Mwanza Mukombo", "Mwape Mialo", "Mwepu Ilunga", "Nabil Bentaleb",
  "Nabil Ghilas", "Nacer Abdellah", "Nacer Chadli", "Nacerdine Drid",
  "Nader Mohammadkhani", "Nadhim Shaker Salim", "Nadir Belhadj", "Naeem Saad",
  "Naeim Saadavi", "Naif Al-Qadi", "Nam Song-Chol", "Nani",
  "Naohiro Takahara", "Naoki Matsuda", "Naoki Soma", "Nasir Khamees",
  "Nasko Sirakov", "Nasrollah Abdollahi", "Nasser Hejazi", "Nasser Nouraei",
  "Nassir Al-Ghanim", "Nastja Čeh", "Natiq Hashim Abidoun", "Nawaf Al-Temyat",
  "Ndaye Mulamba", "Necula Răducanu", "Néicer Reasco", "Neil Covone",
  "Neil Sullivan", "Neil Webb", "Nejc Pečnik", "Néjib Ghommidh",
  "Néjib Liman", "Nelinho", "Nélson", "Nelson Cuevas",
  "Nelson Gutiérrez", "Nelson Parraguez", "Nelson Tapia", "Nelson Valdez",
  "Nelson Vivas", "Nenad Đorđević", "Nenad Milijaš", "Nenad Stojković",
  "Nery Pumpido", "Néstor Clausen", "Néstor Fabbri", "Néstor Lorenzo",
  "Néstor Ortigoza", "Néstor Ortiz", "Nestor Subiat", "Néstor Togneri",
  "Neven Subotić", "Niall Quinn", "Nick Rimando", "Nicklas Bendtner",
  "Niclas Alexandersson", "Niclas Jensen", "Nico Claesen", "Nico Van Kerckhoven",
  "Nicola Berti", "Nicolae Dobrin", "Nicolae Lupescu", "Nicolae Pescaru",
  "Nicolas Alnoudji", "Nicolás Asencio", "Nicolás Burdisso", "Nicolas Dewalque",
  "Nicolás Fuentes", "Nicolás Lodeiro", "Nicolas Lombaerts", "Nicolas N'Koulou",
  "Nicolás Olivera", "Nigel de Jong", "Nigel Martyn", "Nigel Worthington",
  "Nihat Kahveci", "Nikica Jelavić", "Nikita Rukavytsya", "Niklas Nyhlén",
  "Niko Kovač", "Niko Kranjčar", "Nikola Jovanović", "Nikola Žigić",
  "Nikolay Arabov", "Nikolay Iliev", "Nikolay Kiselyov", "Nikolay Larionov",
  "Nikos Machlas", "Nikos Nioplias", "Nikos Spiropoulos", "Nikos Tsiantakis",
  "Nilmar", "Nima Nakisa", "Niša Saveljić", "Nobby Stiles",
  "Nobuyuki Kojima", "Noel Brotherston", "Noel Valladares", "Noh Jung-Yoon",
  "Noh Soo-Jin", "Norbert Eder", "Norbert Nigbur", "Norberto Alonso",
  "Norberto Scoponi", "Norio Omura", "Norman Hunter", "Norman Whiteside",
  "Noureddine Bouyahyaoui", "Noureddine Naybet", "Nourredine Kourichi", "Nuno Frechaut",
  "Nuno Valente", "Obafemi Martins", "Obeid Al-Dosari", "Odilon Polleunis",
  "Ogenyi Onazi", "Ognjen Koroman", "Ognjen Petrović", "Ognjen Vranješ",
  "Ognjen Vukojević", "Oguchi Onyewu", "Oh Beom-Seok", "Oh Yun-Kyo",
  "Ohman Chehaibi", "Okan Buruk", "Ola By Rise", "Olaf Heredia",
  "Olaf Marschall", "Olaf Thon", "Ole Gunnar Solskjær", "Ole Qvist",
  "Oleg Blokhin", "Oleg Romantsev", "Oleg Salenko", "Oleg Shatov",
  "Oleh Blokhin", "Oleh Husyev", "Oleh Kuznetsov", "Oleh Protasov",
  "Oleh Shelayev", "Oleksandr Shovkovskyi", "Oleksandr Yatsenko", "Oleksandr Zavarov",
  "Oleksiy Byelik", "Oliver Bierhoff", "Oliver Bozanić", "Oliver Kovačević",
  "Oliver Neuville", "Oliver Zelenika", "Olivier Rouyer", "Olle Nordin",
  "Olof Mellberg", "Omar Al-Ghamdi", "Omar Bravo", "Omar Caetano",
  "Omar Daf", "Omar Diallo", "Omar Gonzalez", "Omar Larrosa",
  "Omari Tetradze", "Ömer Çatkıç", "Onandi Lowe", "Orestis Karnezis",
  "Oribe Peralta", "Örjan Persson", "Orlando de la Torre", "Osama Oraby",
  "Oscar", "Oscar Arizaga", "Óscar Bagüí", "Óscar Cardozo",
  "Óscar Córdoba", "Óscar Cortés", "Óscar Duarte", "Oscar Eyobo",
  "Oscar García", "Oscar Garré", "Oscar Ortiz", "Óscar Pérez",
  "Oscar Ramírez", "Oscar Rojas", "Oscar Ruggeri", "Óscar Sánchez",
  "Óscar Ustari", "Oscar Wirth", "Oscar Zubia", "Osman Chávez",
  "Osvaldo Ardiles", "Osvaldo Castro", "Oswaldo Ibarra", "Oswaldo Ramírez",
  "Oswaldo Sánchez", "Otto Addo", "Otto Konrad", "Ottorino Sartor",
  "Ou Chuliang", "Ouro-Nimini Tchagnirou", "Ousmane Viera", "Ove Grahn",
  "Ove Kindvall", "Ovidiu Stîngă", "Owen Hargreaves", "Pablo",
  "Pablo Aimar", "Pablo Armero", "Pablo Barrera", "Pablo Bengoechea",
  "Pablo Cavallero", "Pablo Chinchilla", "Pablo Contreras", "Pablo Forlán",
  "Pablo García", "Pablo Larios", "Pablo Mastroeni", "Pablo Paz",
  "Packie Bonner", "Pak Chol-Jin", "Pak Nam-Chol", "Pak Sung-Hyok",
  "## -, Palencia", "Panagiotis Glykos", "Panagiotis Kone", "Panagiotis Tachtsidis",
  "Pantelis Kapetanos", "Paolo Conti", "Paolo Montero", "Paolo Pulici",
  "Paolo Rossi", "Papa Bouba Diop", "Papa Malick Diop", "Pape Sarr",
  "Pape Thiaw", "Park Chang-Sun", "Park Chu-Young", "Park Chul-Woo",
  "Park Ji-Sung", "Park Jong-Woo", "Park Joo-Ho", "Park Jung-bae",
  "Park Kyung-Hoon", "Parviz Broumand", "Pascal Chimbonda", "Pascal Plovie",
  "Pascal Renier", "Pascal Zuberbühler", "Pasquale De Luca", "Pat Jennings",
  "Patrice Abanda", "Patrice Rio", "Patricio Hernández", "Patricio Urrutia",
  "Patricio Yáñez", "Patrick Battiston", "Patrick M'Boma", "Patrick Mtiliga",
  "Patrick Müller", "Patrick Pemberton", "Patrick Suffo", "Patrick Sylvestre",
  "Patrick Vervoort", "Patrik Andersson", "Patrizio Sala", "Paul Aguilar",
  "Paul Ambrosi", "Paul Bahoken", "Paul Breitner", "Paul Caligiuri",
  "Paul Dolan", "Paul Evans", "Paul Hall", "Paul Ince",
  "Paul James", "Paul Krumpe", "Paul Lambert", "Paul Loga",
  "Paul Mariner", "Paul McGrath", "Paul McStay", "Paul Parker",
  "Paul Ramsey", "Paul Robinson", "Paul Steiner", "Paul Sturrock",
  "Paul Van Himst", "Paul Verhaegh", "Paulinho", "Paulo Bento",
  "Paulo Cézar", "Paulo da Silva", "Paulo Ferreira", "Paulo Futre",
  "Paulo Isidoro", "Paulo Santos", "Paulo Sérgio", "Paulo Sousa",
  "Paulo Vitor", "Paulo Wanchope", "Pavel Chaloupka", "Pavel Mareš",
  "Pavel Panov", "Pável Pardo", "Pavel Yakovenko", "Paweł Brożek",
  "Paweł Janas", "Paweł Kryszałowicz", "Paweł Sibik", "Pedrinho",
  "Pedro", "Pedro Barbosa", "Pedro Contreras", "Pedro González",
  "Pedro Mendes", "Pedro Monzón", "Pedro Pablo León", "Pedro Pasculli",
  "Pedro Reyes", "Pedro Rocha", "Pedro Sarabia", "Pedro Soto",
  "Pedro Troglio", "Pedro Uralde", "Pejman Montazeri", "Pelé",
  "Pepe", "Pepe Reina", "Per Frandsen", "Per Frimann",
  "Per Krøldrup", "Per Mertesacker", "Percy Rojas", "Perica Ognjenović",
  "Petar Aleksandrov", "Petar Houbchev", "Petar Krpan", "Petar Mihtarski",
  "Petar Petrov", "Petar Zhekov", "Peter Artner", "Peter Bonetti",
  "Peter Cargill", "Peter Cormack", "Peter Crouch", "Peter Dietrich",
  "Péter Disztl", "Peter Ducke", "Peter Fieber", "Péter Hannich",
  "Peter Kjær", "Peter Løvenkrands", "Peter Larsson", "Peter Lorimer",
  "Peter Møller", "Peter Madsen", "Peter Odemwingie", "Peter Ollerton",
  "Peter Osgood", "Peter Palúch", "Peter Pekarík", "Peter Persidis",
  "Peter Reid", "Peter Rufai", "Peter Schöttel", "Peter Shilton",
  "Peter Simonsen", "Peter Stöger", "Péter Török", "Peter Van Der Heyden",
  "Peter van Vossen", "Peter Vermes", "Peter Wilson", "Peter Withe",
  "Petit", "Petr Janečka", "Petter Hansson", "Phil Babb",
  "Phil Jagielka", "Phil Jones", "Phil Masinga", "Phil Neal",
  "Phil Thompson", "Philip Hughes", "Philipp Degen", "Philippe Albert",
  "Philippe Bergeroo", "Philippe Christanval", "Philippe Clement", "Philippe Desmet",
  "Philippe Mahut", "Philippe Senderos", "Philippe Vande Walle", "Philippe Vercruysse",
  "Philippe Vorbe", "Phillip Cocu", "Piazza", "Pierino Prati",
  "Pierluigi Casiraghi", "Pierluigi Cera", "Pierre Bayonne", "Pierre Carteus",
  "Pierre Issa", "Pierre Littbarski", "Pierre Njanka", "Pierre van Hooijdonk",
  "Pierre Webó", "Pierre Wome", "Piet Keizer", "Piet Schrijvers",
  "Piet Wildschut", "Pietro Anastasi", "Pietro Vierchowod", "Pim Doesburg",
  "Piotr Giza", "Piotr Mowlik", "Piotr Skrobowski", "Piotr Świerczewski",
  "Piotr Trochowski", "Pirmin Schwegler", "Pirri", "Pius Ikedia",
  "Pius N'Diefi", "Plamen Getov", "Plamen Markov", "Plamen Nikolov",
  "Pleun Strik", "Polozzi", "Pontus Farnerud", "Pontus Kåmark",
  "Porfirio Betancourt", "Preben Elkjær Larsen", "Predrag Đorđević", "Predrag Mijatović",
  "Predrag Pašić", "Predrag Radosavljević", "Predrag Spasić", "Přemysl Bičovský",
  "Prince Tagoe", "Prudencio Norales", "Qi Hong", "Qu Bo",
  "Quim", "Quincy Owusu-Abeyie", "Quini", "Quinton Fortune",
  "Quique", "Quique Setién", "Raad Hammoudi Salman", "Rabah Madjer",
  "Rabie Yassin", "Rabiu Afolabi", "Rachamim Talbi", "Rachid Azzouzi",
  "Rachid Daoudi", "Rachid Harkouk", "Rachid Neqrouz", "Rachid Rokki",
  "Radhi Jaïdi", "Radhouane Salhi", "Radosław Kałużny", "Radosław Majdan",
  "Radosław Sobolewski", "Radosav Petrović", "Radoslav Kováč", "Radoslav Zabavník",
  "Radoslav Zdravkov", "Radostin Kishishev", "Radu Niculescu", "Radu Nunweiller",
  "Rafa Silva", "Rafael Alkorta", "Rafael Amador", "Rafael García",
  "Rafael González", "Rafael Gordillo", "Rafael Márquez", "Rafael Martín Vázquez",
  "Rafael Paz", "Rafik Djebbour", "Rafik Halliche", "Rafik Saïfi",
  "Rahman Ahmadi", "Rahman Rezaei", "Raí", "Raimond Aumann",
  "Rainer Bonhof", "Raïs M'Bohli", "Raïs M'Bolhi", "Rajko Tavčar",
  "Ralf Edström", "Ramaz Shengelia", "Rami Shaaban", "Ramires",
  "Ramiro Castillo", "Ramon Azeez", "Ramón Calderé", "Ramón Díaz",
  "Ramón Fagoaga", "Ramón Heredia", "Ramón Hicks", "Ramón Maradiaga",
  "Ramón Medina Bello", "Ramón Mifflin", "Ramón Morales", "Ramón Núñez",
  "Ramón Quiroga", "Ramón Ramírez", "Randall Azofeifa", "Randall Brenes",
  "Randy Ragan", "Randy Samuel", "Raouf Bouzaiene", "Raoul Lambert",
  "Raphaël Wicky", "Rashid Sumaila", "Rashidi Yekini", "Rasoul Khatibi",
  "Rasoul Korbekandi", "Ratko Svilar", "Raúl", "Raúl Albiol",
  "Raúl Gorriti", "Raúl Guerrón", "Raúl Gutiérrez", "Raúl Isiordia",
  "Raúl Jiménez", "Raúl Lara", "Raúl Magaña", "Raul Meireles",
  "Raúl Ormeño", "Raúl Servín", "Ray Clemence", "Ray Houghton",
  "Ray Richards", "Ray Wilkins", "Raymond Kalla", "Raymond Mommens",
  "Razak Pimpong", "Redha Tukar", "Refik Šabanadžović", "Reinaldo",
  "Reinhard Lauck", "Reinhard Libuda", "Reinhold Hintermaier", "Rémy Cabella",
  "Renato", "Renato Gaúcho", "Renato Ibarra", "Renato Zaccarelli",
  "René Girard", "René Henriksen", "René Higuita", "René Houseman",
  "Rene Krhin", "René N'Djeya", "René Valenzuela", "René van de Kerkhof",
  "René Vandereycken", "René Verheyen", "Reneilwe Letsholonyane", "Reto Ziegler",
  "Reuben Gabriel", "Revaz Dzodzuashvili", "Reza Enayati", "Reza Ghoochannejhad",
  "Reza Haghighi", "Reza Shahroudi", "Ri Chol-Myong", "Ri Jun-Il",
  "Ri Kwang-Chon", "Ri Kwang-Hyok", "Ri Myong-Guk", "Riadh Bouazizi",
  "Riadh Jelassi", "Ricardinho", "Ricardo", "Ricardo Álvarez",
  "Ricardo Bochini", "Ricardo Cabanas", "Ricardo Canales", "Ricardo Clark",
  "Ricardo Costa", "Ricardo Gallego", "Ricardo Gardner", "Ricardo Giusti",
  "Ricardo Gomes", "Ricardo La Volpe", "Ricardo Osorio", "Ricardo Pavoni",
  "Ricardo Peláez", "Ricardo Rocha", "Ricardo Rodríguez", "Ricardo Rojas",
  "Ricardo Tavarelli", "Ricardo Villa", "Riccardo Ferri", "Riccardo Montolivo",
  "Richard Báez", "Richard Dunne", "Richard Garcia", "Richard Gough",
  "Richard Kingson", "Richard Morales", "Richard Wilson", "Richard Witschge",
  "Richmond Forson", "Ricki Herbert", "Rickie Lambert", "Ridha El Louze",
  "Rigobert Song", "Rigoberto Cisneros", "Rinat Dasayev", "Rinus Israël",
  "Rio Mavuba", "Rivaldo", "Rivelino", "Rivellino",
  "Rizah Mešković", "Roar Strand", "Rob Lee", "Rob Rensenbrink",
  "Rob Witschge", "Robbie Earle", "Robbie Findley", "Robbie Keane",
  "Robert Fleck", "Robert Gadocha", "Robert Green", "Robert Huth",
  "Robert Jarni", "Robert Koren", "Robert Kovač", "Robert Malm",
  "Robert Pecl", "Robert Prosinečki", "Robert Sara", "Róbert Vittek",
  "Roberto", "Roberto Abbondanzieri", "Roberto Acuña", "Roberto Ayala",
  "Roberto Baggio", "Roberto Bailey", "Roberto Bettega", "Roberto Bonano",
  "Roberto Boninsegna", "Roberto Cabañas", "Roberto Challe", "Roberto Di Matteo",
  "Roberto Dinamite", "Roberto Donadoni", "Roberto Fernández", "Roberto Figueroa",
  "Roberto López Ufarte", "Roberto Mancini", "Roberto Matosas", "Roberto Mosquera",
  "Roberto Mussi", "Roberto Néstor Sensini", "Roberto Perfumo", "Roberto Rivas",
  "Roberto Rojas", "Roberto Rosato", "Roberto Telch", "Roberto Tricella",
  "Rodion Cămătaru", "Rodolfo Dubó", "Rodolfo Gamarra", "Rodolfo Manzo",
  "Rodolfo Rodríguez", "Rodolfo Sandoval", "Rodrigo Barrera", "Rodrigo Cordero",
  "Rodrigo Millar", "Rodrigo Muñoz", "Rodrigo Palacio", "Rodrigo Tello",
  "Rodrigues Neto", "Rogelio Delgado", "Rogelio Farías", "Roger Espinoza",
  "Roger Feutmba", "Róger Flores", "Róger Gómez", "Roger Ljung",
  "Roger Milla", "Roger Nilsen", "Roger Saint-Vil", "Rogério Ceni",
  "Roland Andersson", "Roland Grip", "Roland Hattenberger", "Roland Nilsson",
  "Roland Sandberg", "Rolando", "Rolando Chilavert", "Rolando Fonseca",
  "Rolando García", "Rolf Rüssmann", "Roman Bürki", "Roman Jakóbczak",
  "Roman Mählich", "Roman Shirokov", "Roman Weidenfeller", "Roman Wójcicki",
  "Romaric", "Romário", "Romelu Lukaku", "Romeo Benetti",
  "Ron-Robert Zieler", "Ron Vlaar", "Ronald Åhman", "Ronald de Boer",
  "Ronald Fuentes", "Rónald Gómez", "Rónald González Brenes", "Ronald Koeman",
  "Rónald Marín", "Ronald Worm", "Ronaldão", "Ronaldo",
  "Roni Shuruk", "Ronney Pettersson", "Ronnie Hellström", "Ronnie Whelan",
  "Ronny Johnsen", "Rony Martínez", "Roque Júnior", "Roque Santa Cruz",
  "Rory Fallon", "Rosen Kirilov", "Ross Barkley", "Rostislav Vojáček",
  "Roy Aitken", "Roy Andersson", "Roy Miller", "Roy Myers",
  "Roy Wegerle", "Rúben Amorim", "Rubén Ayala", "Rubén Baraja",
  "Rúben Bareño", "Rubén Cano", "Rubén Corbo", "Rubén Correa",
  "Rubén Darío Hernández", "Rubén Galván", "Rubén Glaria", "Rubén Pagnanini",
  "Rubén Paz", "Rubén Pereira", "Rubén Ruiz Díaz", "Rubén Sosa",
  "Rubén Toribio Díaz", "Rudi Smidts", "Rudi Völler", "Rüdiger Abramczik",
  "Rüdiger Schnuphase", "Rudolf Kargus", "Rui Águas", "Rui Jorge",
  "Rui Marques", "Rumyancho Goranov", "Rune Bratseth", "Ruslan Nigmatullin",
  "Ruslan Pimenov", "Ruslan Rotan", "Russell Latapy", "Rüştü Reçber",
  "Ruud Geels", "Ruud Gullit", "Ruud Hesp", "Ruud Krol",
  "Ryad Boudebouz", "Ryan Babel", "Ryan McGowan", "Ryan Nelsen",
  "Ryszard Komornicki", "Ryszard Tarasiewicz", "Ryuzo Morioka", "Søren Busk",
  "Søren Colding", "Søren Larsen", "Søren Lerby", "Saad Al-Harthi",
  "Saad Al-Houti", "Saber Eid", "Sabri Jaballah", "Sadok Sassi",
  "Saeed Al-Owairan", "Safet Sušić", "Saïd Chiba", "Said Dghay",
  "Said Ghandi", "Sakis Prittas", "Salah Assad", "Salah Larbes",
  "Salahdine Hmied", "Salaheddine Bassir", "Saleh Al-Dawod", "Salif Diao",
  "Salomon Kalou", "Salomón Nazar", "Salomon Olembé", "Salvador Cabañas",
  "Salvador Cabezas", "Salvador Carmona", "Salvador Mariona", "Salvador Salguero",
  "Salvatore Bagni", "Salvatore Bocchetti", "Salvatore Schillaci", "Salvatore Sirigu",
  "Sam Malcolmson", "Sami Al-Hashash", "Sami Al-Jaber", "Sami Khedira",
  "Sami Trabelsi", "Samir Handanović", "Samir Shaker Mahmoud", "Sammir",
  "Sammy Adjei", "Sammy Bossut", "Sammy McIlroy", "Sammy N'Djock",
  "Sammy Nelson", "Samson Siasia", "Samuel Ekeme", "Samuel Eto'o",
  "Samuel Inkoom", "Samuel Ipoua", "Samuel Kuffour", "Sander Boschker",
  "Sándor Gujdár", "Sándor Müller", "Sándor Pintér", "Sándor Sallai",
  "Sándor Zombori", "Sandro Cois", "Sandro Mazzola", "Sandy Jardine",
  "Sani Kaita", "Sanny Åslund", "Santi Cazorla", "Santiago Arias",
  "Santiago Cañizares", "Santiago Cortés", "Santiago Ostolaza", "Santiago Santamaría",
  "Santiago Urquiaga", "Santillana", "Saphir Taïder", "Saša Gajser",
  "Saša Ilić", "Sattar Hamedani", "Saturnino Osorio", "Saud Khariri",
  "Savo Milošević", "Savvas Kofidis", "Sayouba Mandé", "Scot Gemmill",
  "Scott Booth", "Scott Carson", "Scott Chipperfield", "Sead Kolašinac",
  "Sebastián Abreu", "Sebastián Coates", "Sebastián Eguren", "Sebastián Fernández",
  "Sebastian Kehl", "Sebastian Mila", "Sebastiano Nela", "Sébastien Bassong",
  "Sébastien Fournier", "Sébastien Squillaci", "Sebastjan Cimirotič", "Segundo Castillo",
  "Seigo Narazaki", "Seiichiro Maki", "Sejad Salihović", "Selim Ben Achour",
  "Senad Lulić", "Senad Tiganj", "Senijad Ibričić", "Seo Dong-Myung",
  "Seo Jung-Won", "Seol Ki-Hyeon", "Sepp Maier", "Serdar Tasci",
  "Serey Die", "Serge Aurier", "Serge Ducosté", "Serge Racine",
  "Sergei Aleinikov", "Sergei Baltacha", "Sergei Borovsky", "Sergei Fokin",
  "Sergei Gorlukovich", "Sergei Ignashevich", "Sergei Semak", "Sergei Yuran",
  "Sergey Andreyev", "Sergey Rodionov", "Sergey Ryzhikov", "Sergi",
  "Serginho", "Sergio", "Sergio Ahumada", "Sergio Almirón",
  "Sergio Batista", "Sergio Berti", "Sérgio Conceição", "Sergio Gori",
  "Sergio Goycochea", "Sergio Martínez", "Sergio Méndez", "Sergio Mendoza",
  "Sergio Romero", "Sergio Santín", "Sergio Vázquez", "Serhiy Krakovskiy",
  "Serhiy Nazarenko", "Serhiy Rebrov", "Seweryn Gancarczyk", "Seydou Doumbia",
  "Shaka Hislop", "Shaker Mahmoud Hamza", "Shane Smeltz", "Shao Jiayi",
  "Shaun Bartlett", "Shaun Wright-Phillips", "Shay Given", "Shin Hong-Gi",
  "Shinji Okazaki", "Shinji Ono", "Shmuel Rosenthal", "Shoji Jo",
  "Shola Ameobi", "Shraga Bar", "Shu-Aib Walters", "Shūichi Gonda",
  "Shunsuke Nakamura", "Shusaku Nishikawa", "Siaka Tiéné", "Siboniso Gaxa",
  "Sibusiso Zuma", "Sidney Govou", "Siegmar Wätzlich", "Sigfried Held",
  "Sigifredo Mercado", "Sigurd Rushfeldt", "Silas", "Silvestre Varela",
  "Silvio Aquino", "Silvio Marić", "Silviu Lung", "Simão",
  "Šime Vrsaljko", "Simeon Simeonov", "Simon Donnelly", "Simon Elliott",
  "Simon Gopane", "Simon Kjær", "Simon Mignolet", "Simon Poulsen",
  "Simon Tchobang", "Simone Barone", "Simone Pepe", "Simone Perrotta",
  "Sinha", "Siniša Mihajlović", "Siphiwe Tshabalala", "Sirajeddine Chihi",
  "Sirous Dinmohammadi", "Siyabonga Nomvethe", "Siyabonga Sangweni", "Skander Souayah",
  "Slah Karoui", "Slava Metreveli", "Slaven Bilić", "Slaviša Jokanović",
  "Slobodan Komljenović", "Smahi Triki", "Sócrates", "Sofiane Feghouli",
  "Sofiane Melliti", "Sohrab Bakhtiarizadeh", "Sokratis Papastathopoulos", "Son Heung-Min",
  "Song Chong-Gug", "Sotirios Kyrgiakos", "Sotiris Ninis", "Souleymane Camara",
  "Souleymanou Hamidou", "Spasoje Bulajič", "Spiros Marangos", "Srečko Katanec",
  "Staffan Tapper", "Ståle Solbakken", "Stan Lazaridis", "Stan Valckx",
  "Stanislav Cherchesov", "Stanislav Griga", "Stanislav Karasi", "Stanislav Seman",
  "Stanislav Šesták", "Stanley Menzo", "Stefan Aladzhov", "Stefan de Vrij",
  "Stefan Effenberg", "Stefan Kießling", "Stefan Kuntz", "Stefan Majewski",
  "Stefan Pettersson", "Ştefan Preda", "Stefan Rehn", "Stefan Reuter",
  "Stefan Schwarz", "Stefan Staykov", "Stefan Velichkov", "Stefano Tacconi",
  "Stefanos Kapino", "Steffen Freund", "Stelios Malezas", "Stelios Manolas",
  "Sten Pålsson", "Stephan Andersen", "Stephan Engels", "Stephan Lehmann",
  "Stephan Lichtsteiner", "Stéphane Chapuisat", "Stéphane Demol", "Stéphane Grichting",
  "Stéphane Guivarc'h", "Stéphane Mbia", "Stéphane Ruffier", "Stéphane Van Der Heyden",
  "Stephen Ahorlu", "Stephen Appiah", "Stephen Keshi", "Stephen Malcolm",
  "Stephen Tataw", "Stephen Warnock", "Stere Adamache", "Stern John",
  "Steve Archibald", "Steve Bull", "Steve Cherundolo", "Steve Coppell",
  "Steve Finnan", "Steve Foster", "Steve Gohouri", "Steve Hodge",
  "Steve Mandanda", "Steve McMahon", "Steve McManaman", "Steve Nicol",
  "Steve Penney", "Steve Staunton", "Steve Sumner", "Steve Trittschuh",
  "Steve von Bergen", "Steve Wooddin", "Steven Adams", "Steven Beitashour",
  "Steven Bryce", "Steven Defour", "Steven Lustü", "Steven Pienaar",
  "Steven Reid", "Stewart Downing", "Stewart McKimmie", "Stig Inge Bjørnebye",
  "Stig Tøfting", "Stijn Schaars", "Stipe Pletikosa", "Stjepan Deverić",
  "Stjepan Tomas", "Stoyan Yordanov", "Stoycho Mladenov", "Stoycho Stoilov",
  "Stratos Apostolakis", "Stuart Holden", "Stuart Kennedy", "Stuart McCall",
  "Su Maozhen", "Suad Filekovič", "Sulley Muntari", "Sun Jihai",
  "Sunday Oliseh", "Surprise Moriri", "Sven Andersson", "Sven-Gunnar Larsson",
  "Sven Habermann", "Sven Lindman", "Sven Vermant", "Sylvain Gbohouo",
  "Sylvain N'Diaye", "Sylvain Wiltord", "Tab Ramos", "Tadeusz Dolny",
  "Taffarel", "Tahar El Khalej", "Taher Abouzaid", "Takashi Fukunishi",
  "Takashi Hirano", "Takayuki Morimoto", "Takayuki Suzuki", "Talal Jebreen",
  "Tarak Dhiab", "Tarcisio Burgnich", "Tarek Soliman", "Tarek Thabet",
  "Taribo West", "Tasos Mitropoulos", "Taye Taiwo", "Tayfur Havutçu",
  "Teboho Mokoena", "Teddy Lucic", "Tedj Bensaoula", "Teko Modise",
  "Témime Lahzami", "Tengiz Sulakvelidze", "Teófilo Cubillas", "Teófilo Gutiérrez",
  "Terence Kongolo", "Terry Butcher", "Terry Cooper", "Terry Fenwick",
  "Terry McDermott", "Terry Moore", "Terry Phelan", "Teruyoshi Ito",
  "Teruyuki Moniwa", "Thabang Molefe", "Thabet El-Batal", "Thabo Mngomeni",
  "Thanasis Kolitsidakis", "Thanduyise Khuboni", "Themba Mnguni", "Theo Custers",
  "Theo de Jong", "Theo Snelders", "Theo Walcott", "Theodore Whitmore",
  "Theofanis Gekas", "Théophile Abega", "Thiago Motta", "Thierry Tusseau",
  "Thomas Ahlström", "Thomas Allofs", "Thomas Berthold", "Thomas Bickel",
  "Thomas Dooley", "Thomas Dossevi", "Thomas Enevoldsen", "Thomas Gravesen",
  "Thomas Häßler", "Thomas Helmer", "Thomas Helveg", "Thomas Hitzlsperger",
  "Thomas Kahlenberg", "Thomas Libiih", "Thomas Linke", "Thomas Myhre",
  "Thomas N'Kono", "Thomas Ravelli", "Thomas Sørensen", "Thomas Sjöberg",
  "Thomas Strunz", "Thomas Vermaelen", "Thomas Wyss", "Thompson Oliha",
  "Thomson Allan", "Tiago", "Tibor Nyilasi", "Tibor Rab",
  "Tibor Selymes", "Tijjani Babangida", "Tim Borowski", "Tim Brown",
  "Tim Cahill", "Tim de Cler", "Tim Flowers", "Tim Howard",
  "Tim Krul", "Tim Matavž", "Tim Wiese", "Timmy Simons",
  "Timo Hildebrand", "Timothy Chandler", "Tino Lettieri", "Tino-Sven Sušić",
  "Tisir Al-Antaif", "Tita", "Titi Buengo", "Tobias Linderoth",
  "Toby Alderweireld", "Todor Kolev", "Tom Boyd", "Tom Forsyth",
  "Tom Turesson", "Tomás", "Tomas Antonelius", "Tomás Boy",
  "Tomas Brolin", "Tomáš Galásek", "Tomáš Kříž", "Tomas Nordahl",
  "Tomas Pineda", "Tomáš Rosický", "Tomáš Skuhravý", "Tomáš Ujfaluši",
  "Tomasz Hajto", "Tomasz Kłos", "Tomasz Kuszczak", "Tomasz Rząsa",
  "Tomasz Wałdoch", "Tomislav Butina", "Tomislav Ivković", "Tommy Cassidy",
  "Tommy Coyne", "Tommy Finney", "Tommy Hutchison", "Tommy Oar",
  "Tommy Smith", "Tommy Svensson", "Tommy Wright", "Tomokazu Myojin",
  "Toni Polster", "Toni Šunjić", "Toninho", "Toninho Cerezo",
  "Tony Cascarino", "Tony Dorigo", "Tony Lochhead", "Tony Meola",
  "Tony Popovic", "Tony Sanneh", "Tony Sylva", "Tony Woodcock",
  "Torbjörn Nilsson", "Tore André Flo", "Torsten Frings", "Tosh McKinlay",
  "Toshihide Saito", "Toshihiro Aoyama", "Toshihiro Hattori", "Tostão",
  "Tranquillo Barnetta", "Trevor Brooking", "Trevor Francis", "Trevor Sinclair",
  "Trevor Steven", "Trifon Ivanov", "Troels Rasmussen", "Tsanko Tsvetanov",
  "Tsepo Masilela", "Tshinabu Wa Munda", "Tsonyo Vasilev", "Tsuneyasu Miyamoto",
  "Tubilandu Ndimbi", "Tugay Kerimoğlu", "Txiki Begiristain", "Ubaldo Fillol",
  "Uche Nwofor", "Uche Okafor", "Uche Okechukwu", "Ugo Ferrante",
  "Łukasz Fabiański", "Ulf Kirsten", "Uli Hoeneß", "Uli Stein",
  "Uli Stielike", "Ulises de la Cruz", "Ulrich Ramé", "Ulrich van Gobbel",
  "Ulrik Jansson", "Ümit Özat", "Urruti", "Uwa Echiéjilé",
  "Uwa Elderson Echiéjilé", "Uwe Bein", "Uwe Rahn", "Uwe Reinders",
  "Uwe Seeler", "Václav Migas", "Václav Němeček", "Vadym Yevtushenko",
  "Vagiz Khidiyatullin", "Vahid Halilhodžić", "Vahid Hashemian", "Vahid Talebloo",
  "Vaios Karagiannis", "Valdir Peres", "Valdo", "Valdomiro",
  "Valentin Afonin", "Valentin Stocker", "Valeri Broshin", "Valeri Karpin",
  "Valeriy Porkujan", "Valery Karpin", "Valery Zikov", "Valon Behrami",
  "Valter Birsa", "Vampeta", "Vangelis Moras", "Vasil Dragolov",
  "Vasil Mitkov", "Vasile Gergely", "Vasili Berezutski", "Vasilis Dimitriadis",
  "Vasilis Torosidis", "Vasiliy Rats", "Vasyl Rats", "Vedad Ibišević",
  "Vedran Ćorluka", "Vegard Heggem", "Velimir Zajec", "Velko Yotov",
  "Venancio Ramos", "Víctor", "Víctor Aristizábal", "Víctor Bernárdez",
  "Víctor Cáceres", "Víctor Diogo", "Víctor Espárrago", "Víctor Ibarbo",
  "Victor Ikpeba", "Victor Moses", "Victor N'Dip", "Victor Núñez",
  "Victor Obinna", "Víctor Rangel", "Vidar Riseth", "Vieirinha",
  "Vikash Dhorasoo", "Viktor Chanov", "Viktor Fayzulin", "Viktor Onopko",
  "Viktor Serebryanikov", "Viliam Hýravý", "Vince Grella", "Vincent Aboubakar",
  "Vincent Candela", "Vincent Enyeama", "Vincenzo Grella", "Vincenzo Iaquinta",
  "Vincenzo Montella", "Viola", "Viorel Moldovan", "Virginio Cáceres",
  "Vital Borkelmans", "Vitaly Daraselia", "Vitaly Khmelnitsky", "Vítor Baía",
  "Vítor Damas", "Viv Anderson", "Vladimir Beschastnykh", "Vladimir Bigorra",
  "Vladimir Granat", "Vladimír Hagara", "Vladimír Hrivnák", "Vladimir Jugović",
  "Vladimir Kaplichny", "Vladimír Kinier", "Vladimir Muntyan", "Vladimir Petrović",
  "Vladimir Quesada", "Vladimir Soria", "Vladimir Stojković", "Vladimir Vasilj",
  "Vladimír Weiss", "Vladimiro Schettina", "Vladislav Bogićević", "Vladislav Ternavski",
  "Vladyslav Vashchuk", "Vlastimil Petržela", "Volodymyr Bessonov", "Volodymyr Bezsonov",
  "Volodymyr Lyutyi", "Volodymyr Yezerskyi", "Voro", "Voyn Voynov",
  "Vratislav Lokvenc", "Vujadin Stanojković", "Vyacheslav Chanov", "Vyacheslav Dayev",
  "Vyacheslav Shevchuk", "Vyacheslav Sviderskyi", "Władysław Żmuda", "Włodzimierz Ciołek",
  "Włodzimierz Lubański", "Włodzimierz Mazur", "Włodzimierz Smolarek", "Wagner Lopes",
  "Wakaso Mubarak", "Waldemar Matysik", "Waldir Peres", "Waldo Ponce",
  "Waleed Al-Jasem", "Walter Ayoví", "Walter Boyd", "Walter Centeno",
  "Walter Corbo", "Walter Gargano", "Walter Kogler", "Walter Mantegazza",
  "Walter Martínez", "Walter Meeuws", "Walter Schachner", "Walter Zenga",
  "Wardy Alfaro", "Warren Barrett", "Waylon Francis", "Wayne Bridge",
  "Wellington Sánchez", "Werner Friese", "Wes Brown", "Wesley Sonck",
  "Wilfred Agbonavbare", "Wilfried Bony", "Wilfried Hannes", "Wilfried Louis",
  "Wilfried Puis", "Wilfried Van Moer", "Wilhelm Kreuz", "Willem Jackson",
  "Willem van Hanegem", "Willi Schulz", "William Ayache", "William Carvalho",
  "William Castro", "William Gallas", "William Kvist", "William Mokoena",
  "William Okpara", "William Sunsing", "Willian", "Willie Donachie",
  "Willie Johnston", "Willie Miller", "Willie Morgan", "Willy Sagnol",
  "Willy van de Kerkhof", "Wilmar Cabrera", "Wilmer Cabrera", "Wilmer López",
  "Wilner Nazaire", "Wilner Piquant", "Wilson Oruma", "Wilson Palacios",
  "Wilson Pérez", "Wim Jansen", "Wim Jonk", "Wim Kieft",
  "Wim Rijsbergen", "Wim Suurbier", "Winston Bogarde", "Winston Parks",
  "Winston Reid", "Wojciech Rudy", "Wolfgang Blochwitz", "Wolfgang Dremmler",
  "Wolfgang Feiersinger", "Wolfgang Kleff", "Wolfgang Knaller", "Wolfgang Overath",
  "Wolfgang Rolff", "Wolfgang Seguin", "Wolfgang Weber", "Wolfram Löwe",
  "Wu Chengying", "Wynton Rufer", "Xavi", "Xavier Margairaz",
  "Xherdan Shaqiri", "Xu Yunlong", "Yıldıray Baştürk", "Yacine Bentalaa",
  "Yacine Brahimi", "Yahya Golmohammadi", "Yair Nossovsky", "Yakubu Aiyegbeni",
  "Yang Chen", "Yang Pu", "Yann Sommer", "Yannick Stopyra",
  "Yao Aziawonou", "Yao Junior Sènaya", "Yasser Al-Qahtani", "Yassine Chikhaoui",
  "Yassir Al-Taifi", "Yasuhito Endo", "Yasuyuki Konno", "Yazid Mansouri",
  "Yechezekel Chazom", "Yechiel Hameiri", "Yegor Titov", "Yehoshua Feigenbaum",
  "Yeltsin Tejeda", "Yeom Ki-Hun", "Yisha'ayahu Schwager", "Yitzchak Vissoker",
  "Yoann Gourcuff", "Yochanan Vollach", "Yohan Cabaye", "Yoichi Doi",
  "Yoichiro Kakitani", "Yoo Byung-Ok", "Yoo Sang-Chul", "Yoon Deuk-Yeo",
  "Yoon Jung-Hwan", "Yordan Letchkov", "Yoshikatsu Kawaguchi", "Yoshito Ōkubo",
  "Youssef Chippo", "Youssef Rossi", "Yousuf Al-Thunayan", "Yousuf Hussain",
  "Yu Genwei", "Yūichi Komano", "Yuji Nakazawa", "Yuki Abe",
  "Yun Suk-Young", "Yuri Gavrilov", "Yuri Kovtun", "Yuri Lodygin",
  "Yuri Nikiforov", "Yuri Susloparov", "Yuri Zhirkov", "Yussef Al-Suwayed",
  "Yutaka Akita", "Yuto Nagatomo", "Yuya Osako", "Yvan Quentin",
  "Yves Vanderhaeghe", "Øyvind Leonhardsen", "Yvon Le Roux", "Zafer Özgültekin",
  "Zakaria Alaoui", "Zbigniew Boniek", "Zbigniew Gut", "Zdeněk Grygera",
  "Zdeněk Hruška", "Zdeněk Nehoda", "Zdeno Štrba", "Zdravko Kuzmanović",
  "Zdravko Zdravkov", "Zdzisław Kapka", "Zdzisław Kostrzewa", "Zé Carlos",
  "Zé Kalanga", "Zé Maria", "Zé Roberto", "Zé Sérgio",
  "Željko Kalac", "Željko Milinovič", "Željko Petrović", "Zetti",
  "Zhang Enhua", "Zhao Junzhe", "Zhivko Gospodinov", "Ziad Jaziri",
  "Zico", "Zinho", "Zlatan Ljubijankič", "Zlatko Dedič",
  "Zlatko Krmpotić", "Zlatko Vujović", "Zlatko Yankov", "Zlatko Zahovič",
  "Zoltán Kereki", "Zoltán Péter", "Zoran Mamić", "Zoran Mirković",
  "Zoran Pavlović", "Zoran Tošić", "Zoran Vujović", "Zoran Vulić",
  "Zoubeir Baya", "Zsolt Muzsnay", "Zuhair Bakhit", "Zvi Rosen",
  "Zvjezdan Misimović", "Zvonimir Boban", "Zvonimir Soldo", "Zvonimir Vukić",
  "Zvonko Živković", "Zygmunt Kalinowski", "Zygmunt Kukla", "Zygmunt Maszczyk",
];
